//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService.ExWebSvc4Mad {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gravity.exweb.org/", ConfigurationName="ExWebSvc4Mad.ExWebSvcSoap")]
    public interface ExWebSvcSoap {
        
        // CODEGEN: Generating message contract since element name codeClient from namespace http://gravity.exweb.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gravity.exweb.org/GetClient", ReplyAction="*")]
        KoloWin.CustomerService.ExWebSvc4Mad.GetClientResponse GetClient(KoloWin.CustomerService.ExWebSvc4Mad.GetClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gravity.exweb.org/GetClient", ReplyAction="*")]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.GetClientResponse> GetClientAsync(KoloWin.CustomerService.ExWebSvc4Mad.GetClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gravity.exweb.org/GetFrais", ReplyAction="*")]
        int GetFrais(int montant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gravity.exweb.org/GetFrais", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetFraisAsync(int montant);
        
        // CODEGEN: Generating message contract since element name codeClient from namespace http://gravity.exweb.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gravity.exweb.org/ConsulterMad", ReplyAction="*")]
        KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadResponse ConsulterMad(KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gravity.exweb.org/ConsulterMad", ReplyAction="*")]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadResponse> ConsulterMadAsync(KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadRequest request);
        
        // CODEGEN: Generating message contract since element name codeTerminal from namespace http://gravity.exweb.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gravity.exweb.org/SavePmad", ReplyAction="*")]
        KoloWin.CustomerService.ExWebSvc4Mad.SavePmadResponse SavePmad(KoloWin.CustomerService.ExWebSvc4Mad.SavePmadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gravity.exweb.org/SavePmad", ReplyAction="*")]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.SavePmadResponse> SavePmadAsync(KoloWin.CustomerService.ExWebSvc4Mad.SavePmadRequest request);
        
        // CODEGEN: Generating message contract since element name codeTerminal from namespace http://gravity.exweb.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gravity.exweb.org/SaveMad", ReplyAction="*")]
        KoloWin.CustomerService.ExWebSvc4Mad.SaveMadResponse SaveMad(KoloWin.CustomerService.ExWebSvc4Mad.SaveMadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gravity.exweb.org/SaveMad", ReplyAction="*")]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.SaveMadResponse> SaveMadAsync(KoloWin.CustomerService.ExWebSvc4Mad.SaveMadRequest request);
        
        // CODEGEN: Generating message contract since element name number from namespace http://gravity.exweb.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gravity.exweb.org/SendSms", ReplyAction="*")]
        KoloWin.CustomerService.ExWebSvc4Mad.SendSmsResponse SendSms(KoloWin.CustomerService.ExWebSvc4Mad.SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gravity.exweb.org/SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.SendSmsResponse> SendSmsAsync(KoloWin.CustomerService.ExWebSvc4Mad.SendSmsRequest request);
        
        // CODEGEN: Generating message contract since element name regCode from namespace http://gravity.exweb.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gravity.exweb.org/Register", ReplyAction="*")]
        KoloWin.CustomerService.ExWebSvc4Mad.RegisterResponse Register(KoloWin.CustomerService.ExWebSvc4Mad.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gravity.exweb.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.RegisterResponse> RegisterAsync(KoloWin.CustomerService.ExWebSvc4Mad.RegisterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClient", Namespace="http://gravity.exweb.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4Mad.GetClientRequestBody Body;
        
        public GetClientRequest() {
        }
        
        public GetClientRequest(KoloWin.CustomerService.ExWebSvc4Mad.GetClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gravity.exweb.org/")]
    public partial class GetClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codeClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string telephone;
        
        public GetClientRequestBody() {
        }
        
        public GetClientRequestBody(string codeClient, string telephone) {
            this.codeClient = codeClient;
            this.telephone = telephone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClientResponse", Namespace="http://gravity.exweb.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4Mad.GetClientResponseBody Body;
        
        public GetClientResponse() {
        }
        
        public GetClientResponse(KoloWin.CustomerService.ExWebSvc4Mad.GetClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gravity.exweb.org/")]
    public partial class GetClientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetClientResult;
        
        public GetClientResponseBody() {
        }
        
        public GetClientResponseBody(string GetClientResult) {
            this.GetClientResult = GetClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsulterMadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsulterMad", Namespace="http://gravity.exweb.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadRequestBody Body;
        
        public ConsulterMadRequest() {
        }
        
        public ConsulterMadRequest(KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gravity.exweb.org/")]
    public partial class ConsulterMadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codeClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string telephone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string reference;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int montant;
        
        public ConsulterMadRequestBody() {
        }
        
        public ConsulterMadRequestBody(string codeClient, string telephone, string reference, int montant) {
            this.codeClient = codeClient;
            this.telephone = telephone;
            this.reference = reference;
            this.montant = montant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsulterMadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsulterMadResponse", Namespace="http://gravity.exweb.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadResponseBody Body;
        
        public ConsulterMadResponse() {
        }
        
        public ConsulterMadResponse(KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gravity.exweb.org/")]
    public partial class ConsulterMadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsulterMadResult;
        
        public ConsulterMadResponseBody() {
        }
        
        public ConsulterMadResponseBody(string ConsulterMadResult) {
            this.ConsulterMadResult = ConsulterMadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePmadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePmad", Namespace="http://gravity.exweb.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4Mad.SavePmadRequestBody Body;
        
        public SavePmadRequest() {
        }
        
        public SavePmadRequest(KoloWin.CustomerService.ExWebSvc4Mad.SavePmadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gravity.exweb.org/")]
    public partial class SavePmadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codeTerminal;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idCaisse;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idOperateur;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int idMad;
        
        public SavePmadRequestBody() {
        }
        
        public SavePmadRequestBody(string codeTerminal, int idCaisse, int idOperateur, int idMad) {
            this.codeTerminal = codeTerminal;
            this.idCaisse = idCaisse;
            this.idOperateur = idOperateur;
            this.idMad = idMad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePmadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePmadResponse", Namespace="http://gravity.exweb.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4Mad.SavePmadResponseBody Body;
        
        public SavePmadResponse() {
        }
        
        public SavePmadResponse(KoloWin.CustomerService.ExWebSvc4Mad.SavePmadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gravity.exweb.org/")]
    public partial class SavePmadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SavePmadResult;
        
        public SavePmadResponseBody() {
        }
        
        public SavePmadResponseBody(int SavePmadResult) {
            this.SavePmadResult = SavePmadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveMadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveMad", Namespace="http://gravity.exweb.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4Mad.SaveMadRequestBody Body;
        
        public SaveMadRequest() {
        }
        
        public SaveMadRequest(KoloWin.CustomerService.ExWebSvc4Mad.SaveMadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gravity.exweb.org/")]
    public partial class SaveMadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codeTerminal;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idCaisse;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idOperateur;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int idClientEmetteur;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int idClientBeneficiaire;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int montant;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int ccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int tva;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string codeVille;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string reference;
        
        public SaveMadRequestBody() {
        }
        
        public SaveMadRequestBody(string codeTerminal, int idCaisse, int idOperateur, int idClientEmetteur, int idClientBeneficiaire, int montant, int ccion, int tva, string codeVille, string reference) {
            this.codeTerminal = codeTerminal;
            this.idCaisse = idCaisse;
            this.idOperateur = idOperateur;
            this.idClientEmetteur = idClientEmetteur;
            this.idClientBeneficiaire = idClientBeneficiaire;
            this.montant = montant;
            this.ccion = ccion;
            this.tva = tva;
            this.codeVille = codeVille;
            this.reference = reference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveMadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveMadResponse", Namespace="http://gravity.exweb.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4Mad.SaveMadResponseBody Body;
        
        public SaveMadResponse() {
        }
        
        public SaveMadResponse(KoloWin.CustomerService.ExWebSvc4Mad.SaveMadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gravity.exweb.org/")]
    public partial class SaveMadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SaveMadResult;
        
        public SaveMadResponseBody() {
        }
        
        public SaveMadResponseBody(int SaveMadResult) {
            this.SaveMadResult = SaveMadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="http://gravity.exweb.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4Mad.SendSmsRequestBody Body;
        
        public SendSmsRequest() {
        }
        
        public SendSmsRequest(KoloWin.CustomerService.ExWebSvc4Mad.SendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gravity.exweb.org/")]
    public partial class SendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string number;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idUnite;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string other;
        
        public SendSmsRequestBody() {
        }
        
        public SendSmsRequestBody(string number, string message, int idUnite, string other) {
            this.number = number;
            this.message = message;
            this.idUnite = idUnite;
            this.other = other;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="http://gravity.exweb.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4Mad.SendSmsResponseBody Body;
        
        public SendSmsResponse() {
        }
        
        public SendSmsResponse(KoloWin.CustomerService.ExWebSvc4Mad.SendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gravity.exweb.org/")]
    public partial class SendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsResult;
        
        public SendSmsResponseBody() {
        }
        
        public SendSmsResponseBody(string SendSmsResult) {
            this.SendSmsResult = SendSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://gravity.exweb.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4Mad.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(KoloWin.CustomerService.ExWebSvc4Mad.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gravity.exweb.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string regCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string info;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string regCode, string info) {
            this.regCode = regCode;
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://gravity.exweb.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4Mad.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(KoloWin.CustomerService.ExWebSvc4Mad.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gravity.exweb.org/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(string RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExWebSvcSoapChannel : KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExWebSvcSoapClient : System.ServiceModel.ClientBase<KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap>, KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap {
        
        public ExWebSvcSoapClient() {
        }
        
        public ExWebSvcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExWebSvcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExWebSvcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExWebSvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KoloWin.CustomerService.ExWebSvc4Mad.GetClientResponse KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap.GetClient(KoloWin.CustomerService.ExWebSvc4Mad.GetClientRequest request) {
            return base.Channel.GetClient(request);
        }
        
        public string GetClient(string codeClient, string telephone) {
            KoloWin.CustomerService.ExWebSvc4Mad.GetClientRequest inValue = new KoloWin.CustomerService.ExWebSvc4Mad.GetClientRequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4Mad.GetClientRequestBody();
            inValue.Body.codeClient = codeClient;
            inValue.Body.telephone = telephone;
            KoloWin.CustomerService.ExWebSvc4Mad.GetClientResponse retVal = ((KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap)(this)).GetClient(inValue);
            return retVal.Body.GetClientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.GetClientResponse> KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap.GetClientAsync(KoloWin.CustomerService.ExWebSvc4Mad.GetClientRequest request) {
            return base.Channel.GetClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.GetClientResponse> GetClientAsync(string codeClient, string telephone) {
            KoloWin.CustomerService.ExWebSvc4Mad.GetClientRequest inValue = new KoloWin.CustomerService.ExWebSvc4Mad.GetClientRequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4Mad.GetClientRequestBody();
            inValue.Body.codeClient = codeClient;
            inValue.Body.telephone = telephone;
            return ((KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap)(this)).GetClientAsync(inValue);
        }
        
        public int GetFrais(int montant) {
            return base.Channel.GetFrais(montant);
        }
        
        public System.Threading.Tasks.Task<int> GetFraisAsync(int montant) {
            return base.Channel.GetFraisAsync(montant);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadResponse KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap.ConsulterMad(KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadRequest request) {
            return base.Channel.ConsulterMad(request);
        }
        
        public string ConsulterMad(string codeClient, string telephone, string reference, int montant) {
            KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadRequest inValue = new KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadRequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadRequestBody();
            inValue.Body.codeClient = codeClient;
            inValue.Body.telephone = telephone;
            inValue.Body.reference = reference;
            inValue.Body.montant = montant;
            KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadResponse retVal = ((KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap)(this)).ConsulterMad(inValue);
            return retVal.Body.ConsulterMadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadResponse> KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap.ConsulterMadAsync(KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadRequest request) {
            return base.Channel.ConsulterMadAsync(request);
        }
        
        public System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadResponse> ConsulterMadAsync(string codeClient, string telephone, string reference, int montant) {
            KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadRequest inValue = new KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadRequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4Mad.ConsulterMadRequestBody();
            inValue.Body.codeClient = codeClient;
            inValue.Body.telephone = telephone;
            inValue.Body.reference = reference;
            inValue.Body.montant = montant;
            return ((KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap)(this)).ConsulterMadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KoloWin.CustomerService.ExWebSvc4Mad.SavePmadResponse KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap.SavePmad(KoloWin.CustomerService.ExWebSvc4Mad.SavePmadRequest request) {
            return base.Channel.SavePmad(request);
        }
        
        public int SavePmad(string codeTerminal, int idCaisse, int idOperateur, int idMad) {
            KoloWin.CustomerService.ExWebSvc4Mad.SavePmadRequest inValue = new KoloWin.CustomerService.ExWebSvc4Mad.SavePmadRequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4Mad.SavePmadRequestBody();
            inValue.Body.codeTerminal = codeTerminal;
            inValue.Body.idCaisse = idCaisse;
            inValue.Body.idOperateur = idOperateur;
            inValue.Body.idMad = idMad;
            KoloWin.CustomerService.ExWebSvc4Mad.SavePmadResponse retVal = ((KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap)(this)).SavePmad(inValue);
            return retVal.Body.SavePmadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.SavePmadResponse> KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap.SavePmadAsync(KoloWin.CustomerService.ExWebSvc4Mad.SavePmadRequest request) {
            return base.Channel.SavePmadAsync(request);
        }
        
        public System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.SavePmadResponse> SavePmadAsync(string codeTerminal, int idCaisse, int idOperateur, int idMad) {
            KoloWin.CustomerService.ExWebSvc4Mad.SavePmadRequest inValue = new KoloWin.CustomerService.ExWebSvc4Mad.SavePmadRequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4Mad.SavePmadRequestBody();
            inValue.Body.codeTerminal = codeTerminal;
            inValue.Body.idCaisse = idCaisse;
            inValue.Body.idOperateur = idOperateur;
            inValue.Body.idMad = idMad;
            return ((KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap)(this)).SavePmadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KoloWin.CustomerService.ExWebSvc4Mad.SaveMadResponse KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap.SaveMad(KoloWin.CustomerService.ExWebSvc4Mad.SaveMadRequest request) {
            return base.Channel.SaveMad(request);
        }
        
        public int SaveMad(string codeTerminal, int idCaisse, int idOperateur, int idClientEmetteur, int idClientBeneficiaire, int montant, int ccion, int tva, string codeVille, string reference) {
            KoloWin.CustomerService.ExWebSvc4Mad.SaveMadRequest inValue = new KoloWin.CustomerService.ExWebSvc4Mad.SaveMadRequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4Mad.SaveMadRequestBody();
            inValue.Body.codeTerminal = codeTerminal;
            inValue.Body.idCaisse = idCaisse;
            inValue.Body.idOperateur = idOperateur;
            inValue.Body.idClientEmetteur = idClientEmetteur;
            inValue.Body.idClientBeneficiaire = idClientBeneficiaire;
            inValue.Body.montant = montant;
            inValue.Body.ccion = ccion;
            inValue.Body.tva = tva;
            inValue.Body.codeVille = codeVille;
            inValue.Body.reference = reference;
            KoloWin.CustomerService.ExWebSvc4Mad.SaveMadResponse retVal = ((KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap)(this)).SaveMad(inValue);
            return retVal.Body.SaveMadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.SaveMadResponse> KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap.SaveMadAsync(KoloWin.CustomerService.ExWebSvc4Mad.SaveMadRequest request) {
            return base.Channel.SaveMadAsync(request);
        }
        
        public System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.SaveMadResponse> SaveMadAsync(string codeTerminal, int idCaisse, int idOperateur, int idClientEmetteur, int idClientBeneficiaire, int montant, int ccion, int tva, string codeVille, string reference) {
            KoloWin.CustomerService.ExWebSvc4Mad.SaveMadRequest inValue = new KoloWin.CustomerService.ExWebSvc4Mad.SaveMadRequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4Mad.SaveMadRequestBody();
            inValue.Body.codeTerminal = codeTerminal;
            inValue.Body.idCaisse = idCaisse;
            inValue.Body.idOperateur = idOperateur;
            inValue.Body.idClientEmetteur = idClientEmetteur;
            inValue.Body.idClientBeneficiaire = idClientBeneficiaire;
            inValue.Body.montant = montant;
            inValue.Body.ccion = ccion;
            inValue.Body.tva = tva;
            inValue.Body.codeVille = codeVille;
            inValue.Body.reference = reference;
            return ((KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap)(this)).SaveMadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KoloWin.CustomerService.ExWebSvc4Mad.SendSmsResponse KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap.SendSms(KoloWin.CustomerService.ExWebSvc4Mad.SendSmsRequest request) {
            return base.Channel.SendSms(request);
        }
        
        public string SendSms(string number, string message, int idUnite, string other) {
            KoloWin.CustomerService.ExWebSvc4Mad.SendSmsRequest inValue = new KoloWin.CustomerService.ExWebSvc4Mad.SendSmsRequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4Mad.SendSmsRequestBody();
            inValue.Body.number = number;
            inValue.Body.message = message;
            inValue.Body.idUnite = idUnite;
            inValue.Body.other = other;
            KoloWin.CustomerService.ExWebSvc4Mad.SendSmsResponse retVal = ((KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap)(this)).SendSms(inValue);
            return retVal.Body.SendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.SendSmsResponse> KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap.SendSmsAsync(KoloWin.CustomerService.ExWebSvc4Mad.SendSmsRequest request) {
            return base.Channel.SendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.SendSmsResponse> SendSmsAsync(string number, string message, int idUnite, string other) {
            KoloWin.CustomerService.ExWebSvc4Mad.SendSmsRequest inValue = new KoloWin.CustomerService.ExWebSvc4Mad.SendSmsRequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4Mad.SendSmsRequestBody();
            inValue.Body.number = number;
            inValue.Body.message = message;
            inValue.Body.idUnite = idUnite;
            inValue.Body.other = other;
            return ((KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap)(this)).SendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KoloWin.CustomerService.ExWebSvc4Mad.RegisterResponse KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap.Register(KoloWin.CustomerService.ExWebSvc4Mad.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public string Register(string regCode, string info) {
            KoloWin.CustomerService.ExWebSvc4Mad.RegisterRequest inValue = new KoloWin.CustomerService.ExWebSvc4Mad.RegisterRequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4Mad.RegisterRequestBody();
            inValue.Body.regCode = regCode;
            inValue.Body.info = info;
            KoloWin.CustomerService.ExWebSvc4Mad.RegisterResponse retVal = ((KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.RegisterResponse> KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap.RegisterAsync(KoloWin.CustomerService.ExWebSvc4Mad.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4Mad.RegisterResponse> RegisterAsync(string regCode, string info) {
            KoloWin.CustomerService.ExWebSvc4Mad.RegisterRequest inValue = new KoloWin.CustomerService.ExWebSvc4Mad.RegisterRequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4Mad.RegisterRequestBody();
            inValue.Body.regCode = regCode;
            inValue.Body.info = info;
            return ((KoloWin.CustomerService.ExWebSvc4Mad.ExWebSvcSoap)(this)).RegisterAsync(inValue);
        }
    }
}
