//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService.ExEneoSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExWebResponseOfUnpaidBill", Namespace="http://exeneo.expressexchange.fr/")]
    [System.SerializableAttribute()]
    public partial class ExWebResponseOfUnpaidBill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsSuccesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KoloWin.CustomerService.ExEneoSvc.UnpaidBill DataObjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsSucces {
            get {
                return this.IsSuccesField;
            }
            set {
                if ((this.IsSuccesField.Equals(value) != true)) {
                    this.IsSuccesField = value;
                    this.RaisePropertyChanged("IsSucces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public KoloWin.CustomerService.ExEneoSvc.UnpaidBill DataObject {
            get {
                return this.DataObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.DataObjectField, value) != true)) {
                    this.DataObjectField = value;
                    this.RaisePropertyChanged("DataObject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnpaidBill", Namespace="http://exeneo.expressexchange.fr/")]
    [System.SerializableAttribute()]
    public partial class UnpaidBill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BilledCustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillAccountIdField;
        
        private System.DateTime BillGenerationDateField;
        
        private System.DateTime BillDueDateField;
        
        private decimal BillAmountField;
        
        private System.Nullable<System.DateTime> ImportationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestedOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumCompteurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ref4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ref5Field;
        
        private System.Nullable<int> StatutField;
        
        private System.Nullable<decimal> FraisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BillNumber {
            get {
                return this.BillNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BillNumberField, value) != true)) {
                    this.BillNumberField = value;
                    this.RaisePropertyChanged("BillNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BillerId {
            get {
                return this.BillerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BillerIdField, value) != true)) {
                    this.BillerIdField = value;
                    this.RaisePropertyChanged("BillerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BilledCustomerId {
            get {
                return this.BilledCustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BilledCustomerIdField, value) != true)) {
                    this.BilledCustomerIdField = value;
                    this.RaisePropertyChanged("BilledCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BillAccountId {
            get {
                return this.BillAccountIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BillAccountIdField, value) != true)) {
                    this.BillAccountIdField = value;
                    this.RaisePropertyChanged("BillAccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime BillGenerationDate {
            get {
                return this.BillGenerationDateField;
            }
            set {
                if ((this.BillGenerationDateField.Equals(value) != true)) {
                    this.BillGenerationDateField = value;
                    this.RaisePropertyChanged("BillGenerationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime BillDueDate {
            get {
                return this.BillDueDateField;
            }
            set {
                if ((this.BillDueDateField.Equals(value) != true)) {
                    this.BillDueDateField = value;
                    this.RaisePropertyChanged("BillDueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal BillAmount {
            get {
                return this.BillAmountField;
            }
            set {
                if ((this.BillAmountField.Equals(value) != true)) {
                    this.BillAmountField = value;
                    this.RaisePropertyChanged("BillAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> ImportationDate {
            get {
                return this.ImportationDateField;
            }
            set {
                if ((this.ImportationDateField.Equals(value) != true)) {
                    this.ImportationDateField = value;
                    this.RaisePropertyChanged("ImportationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string RequestedOperation {
            get {
                return this.RequestedOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedOperationField, value) != true)) {
                    this.RequestedOperationField = value;
                    this.RaisePropertyChanged("RequestedOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string NumCompteur {
            get {
                return this.NumCompteurField;
            }
            set {
                if ((object.ReferenceEquals(this.NumCompteurField, value) != true)) {
                    this.NumCompteurField = value;
                    this.RaisePropertyChanged("NumCompteur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Ref4 {
            get {
                return this.Ref4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Ref4Field, value) != true)) {
                    this.Ref4Field = value;
                    this.RaisePropertyChanged("Ref4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Ref5 {
            get {
                return this.Ref5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Ref5Field, value) != true)) {
                    this.Ref5Field = value;
                    this.RaisePropertyChanged("Ref5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<int> Statut {
            get {
                return this.StatutField;
            }
            set {
                if ((this.StatutField.Equals(value) != true)) {
                    this.StatutField = value;
                    this.RaisePropertyChanged("Statut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<decimal> Frais {
            get {
                return this.FraisField;
            }
            set {
                if ((this.FraisField.Equals(value) != true)) {
                    this.FraisField = value;
                    this.RaisePropertyChanged("Frais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExWebResponseOfPaidBill", Namespace="http://exeneo.expressexchange.fr/")]
    [System.SerializableAttribute()]
    public partial class ExWebResponseOfPaidBill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsSuccesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KoloWin.CustomerService.ExEneoSvc.PaidBill DataObjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsSucces {
            get {
                return this.IsSuccesField;
            }
            set {
                if ((this.IsSuccesField.Equals(value) != true)) {
                    this.IsSuccesField = value;
                    this.RaisePropertyChanged("IsSucces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public KoloWin.CustomerService.ExEneoSvc.PaidBill DataObject {
            get {
                return this.DataObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.DataObjectField, value) != true)) {
                    this.DataObjectField = value;
                    this.RaisePropertyChanged("DataObject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaidBill", Namespace="http://exeneo.expressexchange.fr/")]
    [System.SerializableAttribute()]
    public partial class PaidBill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubTransactionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillPartnerCompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillPartnerCompanyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillAccountNumberField;
        
        private System.DateTime BillDueDateField;
        
        private decimal PaidAmountField;
        
        private decimal FraisField;
        
        private decimal CcionsField;
        
        private System.Nullable<decimal> MontantTotalField;
        
        private System.DateTime PaidDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaidByMSISDNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeTypeFactureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OMBillPaymentStatusField;
        
        private int IdOperatriceField;
        
        private int IdCaisseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomPayeurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomPayeurField;
        
        private System.Nullable<int> StatutField;
        
        private System.Nullable<bool> StatutReportingField;
        
        private System.Nullable<bool> DegradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperateurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumCompteurField;
        
        private System.Nullable<bool> SentToLiveCashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeTerminalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KoloWin.CustomerService.ExEneoSvc.Caisse CaisseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KoloWin.CustomerService.ExEneoSvc.Operatrice OperatriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SubTransactionType {
            get {
                return this.SubTransactionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubTransactionTypeField, value) != true)) {
                    this.SubTransactionTypeField = value;
                    this.RaisePropertyChanged("SubTransactionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BillPartnerCompanyName {
            get {
                return this.BillPartnerCompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BillPartnerCompanyNameField, value) != true)) {
                    this.BillPartnerCompanyNameField = value;
                    this.RaisePropertyChanged("BillPartnerCompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BillPartnerCompanyCode {
            get {
                return this.BillPartnerCompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BillPartnerCompanyCodeField, value) != true)) {
                    this.BillPartnerCompanyCodeField = value;
                    this.RaisePropertyChanged("BillPartnerCompanyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BillNumber {
            get {
                return this.BillNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BillNumberField, value) != true)) {
                    this.BillNumberField = value;
                    this.RaisePropertyChanged("BillNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string BillAccountNumber {
            get {
                return this.BillAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BillAccountNumberField, value) != true)) {
                    this.BillAccountNumberField = value;
                    this.RaisePropertyChanged("BillAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime BillDueDate {
            get {
                return this.BillDueDateField;
            }
            set {
                if ((this.BillDueDateField.Equals(value) != true)) {
                    this.BillDueDateField = value;
                    this.RaisePropertyChanged("BillDueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal PaidAmount {
            get {
                return this.PaidAmountField;
            }
            set {
                if ((this.PaidAmountField.Equals(value) != true)) {
                    this.PaidAmountField = value;
                    this.RaisePropertyChanged("PaidAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal Frais {
            get {
                return this.FraisField;
            }
            set {
                if ((this.FraisField.Equals(value) != true)) {
                    this.FraisField = value;
                    this.RaisePropertyChanged("Frais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public decimal Ccions {
            get {
                return this.CcionsField;
            }
            set {
                if ((this.CcionsField.Equals(value) != true)) {
                    this.CcionsField = value;
                    this.RaisePropertyChanged("Ccions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<decimal> MontantTotal {
            get {
                return this.MontantTotalField;
            }
            set {
                if ((this.MontantTotalField.Equals(value) != true)) {
                    this.MontantTotalField = value;
                    this.RaisePropertyChanged("MontantTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime PaidDate {
            get {
                return this.PaidDateField;
            }
            set {
                if ((this.PaidDateField.Equals(value) != true)) {
                    this.PaidDateField = value;
                    this.RaisePropertyChanged("PaidDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string PaidByMSISDN {
            get {
                return this.PaidByMSISDNField;
            }
            set {
                if ((object.ReferenceEquals(this.PaidByMSISDNField, value) != true)) {
                    this.PaidByMSISDNField = value;
                    this.RaisePropertyChanged("PaidByMSISDN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string CodeTypeFacture {
            get {
                return this.CodeTypeFactureField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeTypeFactureField, value) != true)) {
                    this.CodeTypeFactureField = value;
                    this.RaisePropertyChanged("CodeTypeFacture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string TransactionStatus {
            get {
                return this.TransactionStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionStatusField, value) != true)) {
                    this.TransactionStatusField = value;
                    this.RaisePropertyChanged("TransactionStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string OMBillPaymentStatus {
            get {
                return this.OMBillPaymentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.OMBillPaymentStatusField, value) != true)) {
                    this.OMBillPaymentStatusField = value;
                    this.RaisePropertyChanged("OMBillPaymentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public int IdOperatrice {
            get {
                return this.IdOperatriceField;
            }
            set {
                if ((this.IdOperatriceField.Equals(value) != true)) {
                    this.IdOperatriceField = value;
                    this.RaisePropertyChanged("IdOperatrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public int IdCaisse {
            get {
                return this.IdCaisseField;
            }
            set {
                if ((this.IdCaisseField.Equals(value) != true)) {
                    this.IdCaisseField = value;
                    this.RaisePropertyChanged("IdCaisse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string NomPayeur {
            get {
                return this.NomPayeurField;
            }
            set {
                if ((object.ReferenceEquals(this.NomPayeurField, value) != true)) {
                    this.NomPayeurField = value;
                    this.RaisePropertyChanged("NomPayeur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string PrenomPayeur {
            get {
                return this.PrenomPayeurField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomPayeurField, value) != true)) {
                    this.PrenomPayeurField = value;
                    this.RaisePropertyChanged("PrenomPayeur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public System.Nullable<int> Statut {
            get {
                return this.StatutField;
            }
            set {
                if ((this.StatutField.Equals(value) != true)) {
                    this.StatutField = value;
                    this.RaisePropertyChanged("Statut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public System.Nullable<bool> StatutReporting {
            get {
                return this.StatutReportingField;
            }
            set {
                if ((this.StatutReportingField.Equals(value) != true)) {
                    this.StatutReportingField = value;
                    this.RaisePropertyChanged("StatutReporting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public System.Nullable<bool> Degrade {
            get {
                return this.DegradeField;
            }
            set {
                if ((this.DegradeField.Equals(value) != true)) {
                    this.DegradeField = value;
                    this.RaisePropertyChanged("Degrade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string Operateur {
            get {
                return this.OperateurField;
            }
            set {
                if ((object.ReferenceEquals(this.OperateurField, value) != true)) {
                    this.OperateurField = value;
                    this.RaisePropertyChanged("Operateur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string NumCompteur {
            get {
                return this.NumCompteurField;
            }
            set {
                if ((object.ReferenceEquals(this.NumCompteurField, value) != true)) {
                    this.NumCompteurField = value;
                    this.RaisePropertyChanged("NumCompteur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=25)]
        public System.Nullable<bool> SentToLiveCash {
            get {
                return this.SentToLiveCashField;
            }
            set {
                if ((this.SentToLiveCashField.Equals(value) != true)) {
                    this.SentToLiveCashField = value;
                    this.RaisePropertyChanged("SentToLiveCash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string CodeTerminal {
            get {
                return this.CodeTerminalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeTerminalField, value) != true)) {
                    this.CodeTerminalField = value;
                    this.RaisePropertyChanged("CodeTerminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public KoloWin.CustomerService.ExEneoSvc.Caisse Caisse {
            get {
                return this.CaisseField;
            }
            set {
                if ((object.ReferenceEquals(this.CaisseField, value) != true)) {
                    this.CaisseField = value;
                    this.RaisePropertyChanged("Caisse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public KoloWin.CustomerService.ExEneoSvc.Operatrice Operatrice {
            get {
                return this.OperatriceField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatriceField, value) != true)) {
                    this.OperatriceField = value;
                    this.RaisePropertyChanged("Operatrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Caisse", Namespace="http://exeneo.expressexchange.fr/")]
    [System.SerializableAttribute()]
    public partial class Caisse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdCaisseField;
        
        private int IdAgenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeMADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretCodeField;
        
        private System.Nullable<int> CodeMGField;
        
        private System.Nullable<int> IdOperatriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeCaisseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenceField;
        
        private System.Nullable<bool> StatutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaskLicenceField;
        
        private System.Nullable<int> IdTerminalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KoloWin.CustomerService.ExEneoSvc.Agence AgenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KoloWin.CustomerService.ExEneoSvc.Device DeviceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KoloWin.CustomerService.ExEneoSvc.Operatrice OperatriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KoloWin.CustomerService.ExEneoSvc.PaidBill[] PaidBillsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdCaisse {
            get {
                return this.IdCaisseField;
            }
            set {
                if ((this.IdCaisseField.Equals(value) != true)) {
                    this.IdCaisseField = value;
                    this.RaisePropertyChanged("IdCaisse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int IdAgence {
            get {
                return this.IdAgenceField;
            }
            set {
                if ((this.IdAgenceField.Equals(value) != true)) {
                    this.IdAgenceField = value;
                    this.RaisePropertyChanged("IdAgence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CodeMAD {
            get {
                return this.CodeMADField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeMADField, value) != true)) {
                    this.CodeMADField = value;
                    this.RaisePropertyChanged("CodeMAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SecretCode {
            get {
                return this.SecretCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SecretCodeField, value) != true)) {
                    this.SecretCodeField = value;
                    this.RaisePropertyChanged("SecretCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> CodeMG {
            get {
                return this.CodeMGField;
            }
            set {
                if ((this.CodeMGField.Equals(value) != true)) {
                    this.CodeMGField = value;
                    this.RaisePropertyChanged("CodeMG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> IdOperatrice {
            get {
                return this.IdOperatriceField;
            }
            set {
                if ((this.IdOperatriceField.Equals(value) != true)) {
                    this.IdOperatriceField = value;
                    this.RaisePropertyChanged("IdOperatrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CodeCaisse {
            get {
                return this.CodeCaisseField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeCaisseField, value) != true)) {
                    this.CodeCaisseField = value;
                    this.RaisePropertyChanged("CodeCaisse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Licence {
            get {
                return this.LicenceField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenceField, value) != true)) {
                    this.LicenceField = value;
                    this.RaisePropertyChanged("Licence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<bool> Statut {
            get {
                return this.StatutField;
            }
            set {
                if ((this.StatutField.Equals(value) != true)) {
                    this.StatutField = value;
                    this.RaisePropertyChanged("Statut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string MaskLicence {
            get {
                return this.MaskLicenceField;
            }
            set {
                if ((object.ReferenceEquals(this.MaskLicenceField, value) != true)) {
                    this.MaskLicenceField = value;
                    this.RaisePropertyChanged("MaskLicence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<int> IdTerminal {
            get {
                return this.IdTerminalField;
            }
            set {
                if ((this.IdTerminalField.Equals(value) != true)) {
                    this.IdTerminalField = value;
                    this.RaisePropertyChanged("IdTerminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public KoloWin.CustomerService.ExEneoSvc.Agence Agence {
            get {
                return this.AgenceField;
            }
            set {
                if ((object.ReferenceEquals(this.AgenceField, value) != true)) {
                    this.AgenceField = value;
                    this.RaisePropertyChanged("Agence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public KoloWin.CustomerService.ExEneoSvc.Device Device {
            get {
                return this.DeviceField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceField, value) != true)) {
                    this.DeviceField = value;
                    this.RaisePropertyChanged("Device");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public KoloWin.CustomerService.ExEneoSvc.Operatrice Operatrice {
            get {
                return this.OperatriceField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatriceField, value) != true)) {
                    this.OperatriceField = value;
                    this.RaisePropertyChanged("Operatrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public KoloWin.CustomerService.ExEneoSvc.PaidBill[] PaidBills {
            get {
                return this.PaidBillsField;
            }
            set {
                if ((object.ReferenceEquals(this.PaidBillsField, value) != true)) {
                    this.PaidBillsField = value;
                    this.RaisePropertyChanged("PaidBills");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operatrice", Namespace="http://exeneo.expressexchange.fr/")]
    [System.SerializableAttribute()]
    public partial class Operatrice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdOperatriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeMADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeMGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        private System.Nullable<int> IdAgencePrincipaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private bool MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KoloWin.CustomerService.ExEneoSvc.Caisse[] CaissesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KoloWin.CustomerService.ExEneoSvc.PaidBill[] PaidBillsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdOperatrice {
            get {
                return this.IdOperatriceField;
            }
            set {
                if ((this.IdOperatriceField.Equals(value) != true)) {
                    this.IdOperatriceField = value;
                    this.RaisePropertyChanged("IdOperatrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CodeMAD {
            get {
                return this.CodeMADField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeMADField, value) != true)) {
                    this.CodeMADField = value;
                    this.RaisePropertyChanged("CodeMAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CodeMG {
            get {
                return this.CodeMGField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeMGField, value) != true)) {
                    this.CodeMGField = value;
                    this.RaisePropertyChanged("CodeMG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> IdAgencePrincipale {
            get {
                return this.IdAgencePrincipaleField;
            }
            set {
                if ((this.IdAgencePrincipaleField.Equals(value) != true)) {
                    this.IdAgencePrincipaleField = value;
                    this.RaisePropertyChanged("IdAgencePrincipale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SecretCode {
            get {
                return this.SecretCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SecretCodeField, value) != true)) {
                    this.SecretCodeField = value;
                    this.RaisePropertyChanged("SecretCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((this.MobileField.Equals(value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public KoloWin.CustomerService.ExEneoSvc.Caisse[] Caisses {
            get {
                return this.CaissesField;
            }
            set {
                if ((object.ReferenceEquals(this.CaissesField, value) != true)) {
                    this.CaissesField = value;
                    this.RaisePropertyChanged("Caisses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public KoloWin.CustomerService.ExEneoSvc.PaidBill[] PaidBills {
            get {
                return this.PaidBillsField;
            }
            set {
                if ((object.ReferenceEquals(this.PaidBillsField, value) != true)) {
                    this.PaidBillsField = value;
                    this.RaisePropertyChanged("PaidBills");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Agence", Namespace="http://exeneo.expressexchange.fr/")]
    [System.SerializableAttribute()]
    public partial class Agence : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdAgenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeAgenceField;
        
        private System.Nullable<int> CodeMgField;
        
        private System.Nullable<int> CodeChangeField;
        
        private System.Nullable<int> CodeSaariField;
        
        private System.Nullable<int> ColumbusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibelleField;
        
        private System.Nullable<int> IdVilleField;
        
        private System.Nullable<int> IdPalierField;
        
        private System.Nullable<int> NumAutoImportField;
        
        private System.Nullable<int> IdContactField;
        
        private System.Nullable<bool> EstOuverteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeGravityField;
        
        private System.Nullable<int> IdGravityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NCodeAgenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KoloWin.CustomerService.ExEneoSvc.Caisse[] CaissesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdAgence {
            get {
                return this.IdAgenceField;
            }
            set {
                if ((this.IdAgenceField.Equals(value) != true)) {
                    this.IdAgenceField = value;
                    this.RaisePropertyChanged("IdAgence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CodeAgence {
            get {
                return this.CodeAgenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeAgenceField, value) != true)) {
                    this.CodeAgenceField = value;
                    this.RaisePropertyChanged("CodeAgence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> CodeMg {
            get {
                return this.CodeMgField;
            }
            set {
                if ((this.CodeMgField.Equals(value) != true)) {
                    this.CodeMgField = value;
                    this.RaisePropertyChanged("CodeMg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> CodeChange {
            get {
                return this.CodeChangeField;
            }
            set {
                if ((this.CodeChangeField.Equals(value) != true)) {
                    this.CodeChangeField = value;
                    this.RaisePropertyChanged("CodeChange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> CodeSaari {
            get {
                return this.CodeSaariField;
            }
            set {
                if ((this.CodeSaariField.Equals(value) != true)) {
                    this.CodeSaariField = value;
                    this.RaisePropertyChanged("CodeSaari");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> ColumbusId {
            get {
                return this.ColumbusIdField;
            }
            set {
                if ((this.ColumbusIdField.Equals(value) != true)) {
                    this.ColumbusIdField = value;
                    this.RaisePropertyChanged("ColumbusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Libelle {
            get {
                return this.LibelleField;
            }
            set {
                if ((object.ReferenceEquals(this.LibelleField, value) != true)) {
                    this.LibelleField = value;
                    this.RaisePropertyChanged("Libelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<int> IdVille {
            get {
                return this.IdVilleField;
            }
            set {
                if ((this.IdVilleField.Equals(value) != true)) {
                    this.IdVilleField = value;
                    this.RaisePropertyChanged("IdVille");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<int> IdPalier {
            get {
                return this.IdPalierField;
            }
            set {
                if ((this.IdPalierField.Equals(value) != true)) {
                    this.IdPalierField = value;
                    this.RaisePropertyChanged("IdPalier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<int> NumAutoImport {
            get {
                return this.NumAutoImportField;
            }
            set {
                if ((this.NumAutoImportField.Equals(value) != true)) {
                    this.NumAutoImportField = value;
                    this.RaisePropertyChanged("NumAutoImport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<int> IdContact {
            get {
                return this.IdContactField;
            }
            set {
                if ((this.IdContactField.Equals(value) != true)) {
                    this.IdContactField = value;
                    this.RaisePropertyChanged("IdContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<bool> EstOuverte {
            get {
                return this.EstOuverteField;
            }
            set {
                if ((this.EstOuverteField.Equals(value) != true)) {
                    this.EstOuverteField = value;
                    this.RaisePropertyChanged("EstOuverte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string CodeGravity {
            get {
                return this.CodeGravityField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeGravityField, value) != true)) {
                    this.CodeGravityField = value;
                    this.RaisePropertyChanged("CodeGravity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<int> IdGravity {
            get {
                return this.IdGravityField;
            }
            set {
                if ((this.IdGravityField.Equals(value) != true)) {
                    this.IdGravityField = value;
                    this.RaisePropertyChanged("IdGravity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string NCodeAgence {
            get {
                return this.NCodeAgenceField;
            }
            set {
                if ((object.ReferenceEquals(this.NCodeAgenceField, value) != true)) {
                    this.NCodeAgenceField = value;
                    this.RaisePropertyChanged("NCodeAgence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public KoloWin.CustomerService.ExEneoSvc.Caisse[] Caisses {
            get {
                return this.CaissesField;
            }
            set {
                if ((object.ReferenceEquals(this.CaissesField, value) != true)) {
                    this.CaissesField = value;
                    this.RaisePropertyChanged("Caisses");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Device", Namespace="http://exeneo.expressexchange.fr/")]
    [System.SerializableAttribute()]
    public partial class Device : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdTerminalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeTerminalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevicePasswordField;
        
        private System.Nullable<int> IdOperateurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VitesseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KoloWin.CustomerService.ExEneoSvc.Caisse[] CaissesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdTerminal {
            get {
                return this.IdTerminalField;
            }
            set {
                if ((this.IdTerminalField.Equals(value) != true)) {
                    this.IdTerminalField = value;
                    this.RaisePropertyChanged("IdTerminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CodeTerminal {
            get {
                return this.CodeTerminalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeTerminalField, value) != true)) {
                    this.CodeTerminalField = value;
                    this.RaisePropertyChanged("CodeTerminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DevicePassword {
            get {
                return this.DevicePasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.DevicePasswordField, value) != true)) {
                    this.DevicePasswordField = value;
                    this.RaisePropertyChanged("DevicePassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> IdOperateur {
            get {
                return this.IdOperateurField;
            }
            set {
                if ((this.IdOperateurField.Equals(value) != true)) {
                    this.IdOperateurField = value;
                    this.RaisePropertyChanged("IdOperateur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Altitude {
            get {
                return this.AltitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.AltitudeField, value) != true)) {
                    this.AltitudeField = value;
                    this.RaisePropertyChanged("Altitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Vitesse {
            get {
                return this.VitesseField;
            }
            set {
                if ((object.ReferenceEquals(this.VitesseField, value) != true)) {
                    this.VitesseField = value;
                    this.RaisePropertyChanged("Vitesse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public KoloWin.CustomerService.ExEneoSvc.Caisse[] Caisses {
            get {
                return this.CaissesField;
            }
            set {
                if ((object.ReferenceEquals(this.CaissesField, value) != true)) {
                    this.CaissesField = value;
                    this.RaisePropertyChanged("Caisses");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExWebResponseOfListOfUnpaidBill", Namespace="http://exeneo.expressexchange.fr/")]
    [System.SerializableAttribute()]
    public partial class ExWebResponseOfListOfUnpaidBill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsSuccesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KoloWin.CustomerService.ExEneoSvc.UnpaidBill[] DataObjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsSucces {
            get {
                return this.IsSuccesField;
            }
            set {
                if ((this.IsSuccesField.Equals(value) != true)) {
                    this.IsSuccesField = value;
                    this.RaisePropertyChanged("IsSucces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public KoloWin.CustomerService.ExEneoSvc.UnpaidBill[] DataObject {
            get {
                return this.DataObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.DataObjectField, value) != true)) {
                    this.DataObjectField = value;
                    this.RaisePropertyChanged("DataObject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://exeneo.expressexchange.fr/", ConfigurationName="ExEneoSvc.ExEneoSoap")]
    public interface ExEneoSoap {
        
        // CODEGEN: Generating message contract since element name numeroFacture from namespace http://exeneo.expressexchange.fr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://exeneo.expressexchange.fr/FindEneoByBillNumber", ReplyAction="*")]
        KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberResponse FindEneoByBillNumber(KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exeneo.expressexchange.fr/FindEneoByBillNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberResponse> FindEneoByBillNumberAsync(KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberRequest request);
        
        // CODEGEN: Generating message contract since element name reference from namespace http://exeneo.expressexchange.fr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://exeneo.expressexchange.fr/FindEneoPaidBillByReference", ReplyAction="*")]
        KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceResponse FindEneoPaidBillByReference(KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exeneo.expressexchange.fr/FindEneoPaidBillByReference", ReplyAction="*")]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceResponse> FindEneoPaidBillByReferenceAsync(KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceRequest request);
        
        // CODEGEN: Generating message contract since element name telephone from namespace http://exeneo.expressexchange.fr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://exeneo.expressexchange.fr/PayENEO", ReplyAction="*")]
        KoloWin.CustomerService.ExEneoSvc.PayENEOResponse PayENEO(KoloWin.CustomerService.ExEneoSvc.PayENEORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exeneo.expressexchange.fr/PayENEO", ReplyAction="*")]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExEneoSvc.PayENEOResponse> PayENEOAsync(KoloWin.CustomerService.ExEneoSvc.PayENEORequest request);
        
        // CODEGEN: Generating message contract since element name numeroContrat from namespace http://exeneo.expressexchange.fr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://exeneo.expressexchange.fr/FindEneoByBillAccount", ReplyAction="*")]
        KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountResponse FindEneoByBillAccount(KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exeneo.expressexchange.fr/FindEneoByBillAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountResponse> FindEneoByBillAccountAsync(KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindEneoByBillNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindEneoByBillNumber", Namespace="http://exeneo.expressexchange.fr/", Order=0)]
        public KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberRequestBody Body;
        
        public FindEneoByBillNumberRequest() {
        }
        
        public FindEneoByBillNumberRequest(KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exeneo.expressexchange.fr/")]
    public partial class FindEneoByBillNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroFacture;
        
        public FindEneoByBillNumberRequestBody() {
        }
        
        public FindEneoByBillNumberRequestBody(string numeroFacture) {
            this.numeroFacture = numeroFacture;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindEneoByBillNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindEneoByBillNumberResponse", Namespace="http://exeneo.expressexchange.fr/", Order=0)]
        public KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberResponseBody Body;
        
        public FindEneoByBillNumberResponse() {
        }
        
        public FindEneoByBillNumberResponse(KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exeneo.expressexchange.fr/")]
    public partial class FindEneoByBillNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KoloWin.CustomerService.ExEneoSvc.ExWebResponseOfUnpaidBill FindEneoByBillNumberResult;
        
        public FindEneoByBillNumberResponseBody() {
        }
        
        public FindEneoByBillNumberResponseBody(KoloWin.CustomerService.ExEneoSvc.ExWebResponseOfUnpaidBill FindEneoByBillNumberResult) {
            this.FindEneoByBillNumberResult = FindEneoByBillNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindEneoPaidBillByReferenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindEneoPaidBillByReference", Namespace="http://exeneo.expressexchange.fr/", Order=0)]
        public KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceRequestBody Body;
        
        public FindEneoPaidBillByReferenceRequest() {
        }
        
        public FindEneoPaidBillByReferenceRequest(KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exeneo.expressexchange.fr/")]
    public partial class FindEneoPaidBillByReferenceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reference;
        
        public FindEneoPaidBillByReferenceRequestBody() {
        }
        
        public FindEneoPaidBillByReferenceRequestBody(string reference) {
            this.reference = reference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindEneoPaidBillByReferenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindEneoPaidBillByReferenceResponse", Namespace="http://exeneo.expressexchange.fr/", Order=0)]
        public KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceResponseBody Body;
        
        public FindEneoPaidBillByReferenceResponse() {
        }
        
        public FindEneoPaidBillByReferenceResponse(KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exeneo.expressexchange.fr/")]
    public partial class FindEneoPaidBillByReferenceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KoloWin.CustomerService.ExEneoSvc.ExWebResponseOfPaidBill FindEneoPaidBillByReferenceResult;
        
        public FindEneoPaidBillByReferenceResponseBody() {
        }
        
        public FindEneoPaidBillByReferenceResponseBody(KoloWin.CustomerService.ExEneoSvc.ExWebResponseOfPaidBill FindEneoPaidBillByReferenceResult) {
            this.FindEneoPaidBillByReferenceResult = FindEneoPaidBillByReferenceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayENEORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayENEO", Namespace="http://exeneo.expressexchange.fr/", Order=0)]
        public KoloWin.CustomerService.ExEneoSvc.PayENEORequestBody Body;
        
        public PayENEORequest() {
        }
        
        public PayENEORequest(KoloWin.CustomerService.ExEneoSvc.PayENEORequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exeneo.expressexchange.fr/")]
    public partial class PayENEORequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string telephone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numeroFacture;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nomDuRemettant;
        
        public PayENEORequestBody() {
        }
        
        public PayENEORequestBody(string telephone, string numeroFacture, string nomDuRemettant) {
            this.telephone = telephone;
            this.numeroFacture = numeroFacture;
            this.nomDuRemettant = nomDuRemettant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayENEOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayENEOResponse", Namespace="http://exeneo.expressexchange.fr/", Order=0)]
        public KoloWin.CustomerService.ExEneoSvc.PayENEOResponseBody Body;
        
        public PayENEOResponse() {
        }
        
        public PayENEOResponse(KoloWin.CustomerService.ExEneoSvc.PayENEOResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exeneo.expressexchange.fr/")]
    public partial class PayENEOResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KoloWin.CustomerService.ExEneoSvc.ExWebResponseOfPaidBill PayENEOResult;
        
        public PayENEOResponseBody() {
        }
        
        public PayENEOResponseBody(KoloWin.CustomerService.ExEneoSvc.ExWebResponseOfPaidBill PayENEOResult) {
            this.PayENEOResult = PayENEOResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindEneoByBillAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindEneoByBillAccount", Namespace="http://exeneo.expressexchange.fr/", Order=0)]
        public KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountRequestBody Body;
        
        public FindEneoByBillAccountRequest() {
        }
        
        public FindEneoByBillAccountRequest(KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exeneo.expressexchange.fr/")]
    public partial class FindEneoByBillAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroContrat;
        
        public FindEneoByBillAccountRequestBody() {
        }
        
        public FindEneoByBillAccountRequestBody(string numeroContrat) {
            this.numeroContrat = numeroContrat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindEneoByBillAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindEneoByBillAccountResponse", Namespace="http://exeneo.expressexchange.fr/", Order=0)]
        public KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountResponseBody Body;
        
        public FindEneoByBillAccountResponse() {
        }
        
        public FindEneoByBillAccountResponse(KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exeneo.expressexchange.fr/")]
    public partial class FindEneoByBillAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KoloWin.CustomerService.ExEneoSvc.ExWebResponseOfListOfUnpaidBill FindEneoByBillAccountResult;
        
        public FindEneoByBillAccountResponseBody() {
        }
        
        public FindEneoByBillAccountResponseBody(KoloWin.CustomerService.ExEneoSvc.ExWebResponseOfListOfUnpaidBill FindEneoByBillAccountResult) {
            this.FindEneoByBillAccountResult = FindEneoByBillAccountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExEneoSoapChannel : KoloWin.CustomerService.ExEneoSvc.ExEneoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExEneoSoapClient : System.ServiceModel.ClientBase<KoloWin.CustomerService.ExEneoSvc.ExEneoSoap>, KoloWin.CustomerService.ExEneoSvc.ExEneoSoap {
        
        public ExEneoSoapClient() {
        }
        
        public ExEneoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExEneoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExEneoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExEneoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberResponse KoloWin.CustomerService.ExEneoSvc.ExEneoSoap.FindEneoByBillNumber(KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberRequest request) {
            return base.Channel.FindEneoByBillNumber(request);
        }
        
        public KoloWin.CustomerService.ExEneoSvc.ExWebResponseOfUnpaidBill FindEneoByBillNumber(string numeroFacture) {
            KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberRequest inValue = new KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberRequest();
            inValue.Body = new KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberRequestBody();
            inValue.Body.numeroFacture = numeroFacture;
            KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberResponse retVal = ((KoloWin.CustomerService.ExEneoSvc.ExEneoSoap)(this)).FindEneoByBillNumber(inValue);
            return retVal.Body.FindEneoByBillNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberResponse> KoloWin.CustomerService.ExEneoSvc.ExEneoSoap.FindEneoByBillNumberAsync(KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberRequest request) {
            return base.Channel.FindEneoByBillNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberResponse> FindEneoByBillNumberAsync(string numeroFacture) {
            KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberRequest inValue = new KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberRequest();
            inValue.Body = new KoloWin.CustomerService.ExEneoSvc.FindEneoByBillNumberRequestBody();
            inValue.Body.numeroFacture = numeroFacture;
            return ((KoloWin.CustomerService.ExEneoSvc.ExEneoSoap)(this)).FindEneoByBillNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceResponse KoloWin.CustomerService.ExEneoSvc.ExEneoSoap.FindEneoPaidBillByReference(KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceRequest request) {
            return base.Channel.FindEneoPaidBillByReference(request);
        }
        
        public KoloWin.CustomerService.ExEneoSvc.ExWebResponseOfPaidBill FindEneoPaidBillByReference(string reference) {
            KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceRequest inValue = new KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceRequest();
            inValue.Body = new KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceRequestBody();
            inValue.Body.reference = reference;
            KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceResponse retVal = ((KoloWin.CustomerService.ExEneoSvc.ExEneoSoap)(this)).FindEneoPaidBillByReference(inValue);
            return retVal.Body.FindEneoPaidBillByReferenceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceResponse> KoloWin.CustomerService.ExEneoSvc.ExEneoSoap.FindEneoPaidBillByReferenceAsync(KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceRequest request) {
            return base.Channel.FindEneoPaidBillByReferenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceResponse> FindEneoPaidBillByReferenceAsync(string reference) {
            KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceRequest inValue = new KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceRequest();
            inValue.Body = new KoloWin.CustomerService.ExEneoSvc.FindEneoPaidBillByReferenceRequestBody();
            inValue.Body.reference = reference;
            return ((KoloWin.CustomerService.ExEneoSvc.ExEneoSoap)(this)).FindEneoPaidBillByReferenceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KoloWin.CustomerService.ExEneoSvc.PayENEOResponse KoloWin.CustomerService.ExEneoSvc.ExEneoSoap.PayENEO(KoloWin.CustomerService.ExEneoSvc.PayENEORequest request) {
            return base.Channel.PayENEO(request);
        }
        
        public KoloWin.CustomerService.ExEneoSvc.ExWebResponseOfPaidBill PayENEO(string telephone, string numeroFacture, string nomDuRemettant) {
            KoloWin.CustomerService.ExEneoSvc.PayENEORequest inValue = new KoloWin.CustomerService.ExEneoSvc.PayENEORequest();
            inValue.Body = new KoloWin.CustomerService.ExEneoSvc.PayENEORequestBody();
            inValue.Body.telephone = telephone;
            inValue.Body.numeroFacture = numeroFacture;
            inValue.Body.nomDuRemettant = nomDuRemettant;
            KoloWin.CustomerService.ExEneoSvc.PayENEOResponse retVal = ((KoloWin.CustomerService.ExEneoSvc.ExEneoSoap)(this)).PayENEO(inValue);
            return retVal.Body.PayENEOResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExEneoSvc.PayENEOResponse> KoloWin.CustomerService.ExEneoSvc.ExEneoSoap.PayENEOAsync(KoloWin.CustomerService.ExEneoSvc.PayENEORequest request) {
            return base.Channel.PayENEOAsync(request);
        }
        
        public System.Threading.Tasks.Task<KoloWin.CustomerService.ExEneoSvc.PayENEOResponse> PayENEOAsync(string telephone, string numeroFacture, string nomDuRemettant) {
            KoloWin.CustomerService.ExEneoSvc.PayENEORequest inValue = new KoloWin.CustomerService.ExEneoSvc.PayENEORequest();
            inValue.Body = new KoloWin.CustomerService.ExEneoSvc.PayENEORequestBody();
            inValue.Body.telephone = telephone;
            inValue.Body.numeroFacture = numeroFacture;
            inValue.Body.nomDuRemettant = nomDuRemettant;
            return ((KoloWin.CustomerService.ExEneoSvc.ExEneoSoap)(this)).PayENEOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountResponse KoloWin.CustomerService.ExEneoSvc.ExEneoSoap.FindEneoByBillAccount(KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountRequest request) {
            return base.Channel.FindEneoByBillAccount(request);
        }
        
        public KoloWin.CustomerService.ExEneoSvc.ExWebResponseOfListOfUnpaidBill FindEneoByBillAccount(string numeroContrat) {
            KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountRequest inValue = new KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountRequest();
            inValue.Body = new KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountRequestBody();
            inValue.Body.numeroContrat = numeroContrat;
            KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountResponse retVal = ((KoloWin.CustomerService.ExEneoSvc.ExEneoSoap)(this)).FindEneoByBillAccount(inValue);
            return retVal.Body.FindEneoByBillAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountResponse> KoloWin.CustomerService.ExEneoSvc.ExEneoSoap.FindEneoByBillAccountAsync(KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountRequest request) {
            return base.Channel.FindEneoByBillAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountResponse> FindEneoByBillAccountAsync(string numeroContrat) {
            KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountRequest inValue = new KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountRequest();
            inValue.Body = new KoloWin.CustomerService.ExEneoSvc.FindEneoByBillAccountRequestBody();
            inValue.Body.numeroContrat = numeroContrat;
            return ((KoloWin.CustomerService.ExEneoSvc.ExEneoSoap)(this)).FindEneoByBillAccountAsync(inValue);
        }
    }
}
