//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class AccountOperationRequest
    {
        public int IdAccountOperationRequest { get; set; }
        public int IdCustomerAccount { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string OperationTypeCode { get; set; }
        public string OperationStatusCode { get; set; }
        public int Amount { get; set; }
    
        public virtual AccountOperation AccountOperation { get; set; }
        public virtual RefOperationStatu RefOperationStatu { get; set; }
        public virtual RefOperationType RefOperationType { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
