//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Business
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Business()
        {
            this.BusinessContacts = new ObservableCollection<BusinessContact>();
            this.BusinessContactUpdateHistories = new ObservableCollection<BusinessContactUpdateHistory>();
        }
    
        public int IdCustomer { get; set; }
        public string IndustryCategoryCode { get; set; }
        public string BusinessName { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual RefIndustryCategory RefIndustryCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<BusinessContact> BusinessContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<BusinessContactUpdateHistory> BusinessContactUpdateHistories { get; set; }
    }
}
