//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBalanceHistory
    {
        public int IdCustomerHistory { get; set; }
        public int IdCustomerAccount { get; set; }
        public string OperationTypeCode { get; set; }
        public Nullable<System.DateTime> HistoryDate { get; set; }
        public int OldBalance { get; set; }
        public int NewBalance { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual RefOperationType RefOperationType { get; set; }
    }
}
