//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerExternalAccount
    {
        public int IdCustomer { get; set; }
        public int IdExternalAccount { get; set; }
    
        public virtual ExternalAccount ExternalAccount { get; set; }
    }
}
