//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class CustomerGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerGroup()
        {
            this.RecurringContributions = new ObservableCollection<RecurringContribution>();
            this.TransfertGroups = new ObservableCollection<TransfertGroup>();
            this.TransfertGroupScheduleds = new ObservableCollection<TransfertGroupScheduled>();
            this.Customers = new ObservableCollection<Customer>();
        }
    
        public int IdCustomerGroup { get; set; }
        public int IdMemberCustomer { get; set; }
        public string GroupTypeCode { get; set; }
        public string GroupName { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual RefGroupType RefGroupType { get; set; }
        public virtual GroupImage GroupImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<RecurringContribution> RecurringContributions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<TransfertGroup> TransfertGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<TransfertGroupScheduled> TransfertGroupScheduleds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Customer> Customers { get; set; }
    }
}
