//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class ExternalAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalAccount()
        {
            this.ExternalAccountHistories = new ObservableCollection<ExternalAccountHistory>();
            this.TransfertE2e = new ObservableCollection<TransfertE2e>();
            this.TransfertE2e1 = new ObservableCollection<TransfertE2e>();
        }
    
        public int IdExternalAccount { get; set; }
        public string ExternalLogin { get; set; }
        public string ExternalPwd { get; set; }
        public string ExternalAccountTypeCode { get; set; }
        public Nullable<int> IdCreditCard { get; set; }
        public int IdCustomer { get; set; }
    
        public virtual CreditCardInfo CreditCardInfo { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<ExternalAccountHistory> ExternalAccountHistories { get; set; }
        public virtual RefExternalAccountType RefExternalAccountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<TransfertE2e> TransfertE2e { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<TransfertE2e> TransfertE2e1 { get; set; }
    }
}
