//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class KoloPermission
    {
        public string ActionCode { get; set; }
        public string GroupCode { get; set; }
        public string ExpirationDate { get; set; }
    
        public virtual KoloGroup KoloGroup { get; set; }
        public virtual KoloSystemAction KoloSystemAction { get; set; }
    }
}
