//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginAttempt
    {
        public int IdLoginAttempt { get; set; }
        public int IdCustomer { get; set; }
        public System.DateTime LoginTime { get; set; }
        public string ResultCode { get; set; }
        public string DeviceId { get; set; }
        public string SimOperator { get; set; }
        public string SimSerialNumber { get; set; }
        public string SubscriberId { get; set; }
        public string Pwd { get; set; }
        public string Number { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Accuracy { get; set; }
    
        public virtual CustomerLogin CustomerLogin { get; set; }
        public virtual RefResult RefResult { get; set; }
    }
}
