//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class MobileDevice
    {
        public int IdMobileDevice { get; set; }
        public string DeviceId { get; set; }
        public string LineNumber { get; set; }
        public string NetworkCountryIso { get; set; }
        public string NetworkOperator { get; set; }
        public string NetworkOperatorName { get; set; }
        public string NetworkType { get; set; }
        public string PhoneType { get; set; }
        public string SimCountryIso { get; set; }
        public string SimOperator { get; set; }
        public string SimOperatorName { get; set; }
        public string SimSerialNumber { get; set; }
        public string SimState { get; set; }
        public string SubscriberId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
