//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class PartnerBalanceHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartnerBalanceHistory()
        {
            this.AccountOperations = new ObservableCollection<AccountOperation>();
            this.Provisions = new ObservableCollection<Provision>();
        }
    
        public int IdPatnerHistory { get; set; }
        public int IdPartnerAccount { get; set; }
        public System.DateTime HistoryDate { get; set; }
        public int OldBalance { get; set; }
        public int NewBalance { get; set; }
        public int Amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<AccountOperation> AccountOperations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Provision> Provisions { get; set; }
    }
}
