//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int IdCustomer { get; set; }
        public string GenderCode { get; set; }
        public string MaritalStatusCode { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CountryCode { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual KoloUser KoloUser { get; set; }
        public virtual RefGender RefGender { get; set; }
        public virtual RefMaritalStatu RefMaritalStatu { get; set; }
        public virtual PersonRelationship PersonRelationship { get; set; }
    }
}
