//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Provision
    {
        public int IdProvision { get; set; }
        public Nullable<int> IdProvisionRequest { get; set; }
        public int IdPatnerHistory { get; set; }
        public int IdResellerPartnerAccount { get; set; }
        public int IdWholesalerPartnerAccount { get; set; }
        public string CodeRefProsisionStatus { get; set; }
        public System.DateTime ProvisionDate { get; set; }
        public int Amount { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Partner Partner1 { get; set; }
        public virtual PartnerBalanceHistory PartnerBalanceHistory { get; set; }
        public virtual RefProvisionStatu RefProvisionStatu { get; set; }
    }
}
