//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopUp
    {
        public int IdTopUp { get; set; }
        public System.DateTime OpDate { get; set; }
        public string PhoneNumber { get; set; }
        public string Amount { get; set; }
        public string OperatorCode { get; set; }
        public int Ccion { get; set; }
        public int IdCustomer { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
