//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferGravity
    {
        public int TransferMadId { get; set; }
        public string GravityReference { get; set; }
        public string KoloReference { get; set; }
        public int KoloSenderId { get; set; }
        public int GravitySenderId { get; set; }
        public int GravityReceiverId { get; set; }
        public int Amount { get; set; }
        public bool Received { get; set; }
        public string ReceiverLastName { get; set; }
        public string ReceiverFirstName { get; set; }
        public string ReceiverPhoneNumber { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
