//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.Poco
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountOperation
    {
        public int IdAccountOperation { get; set; }
        public int IdPartnerAccount { get; set; }
        public string OperationStatusCode { get; set; }
        public int IdPatnerHistory { get; set; }
        public string OperationTypeCode { get; set; }
        public int Amount { get; set; }
    
        public virtual RefOperationStatu RefOperationStatu { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual RefOperationType RefOperationType { get; set; }
        public virtual PartnerBalanceHistory PartnerBalanceHistory { get; set; }
        public virtual AccountOperationRequest AccountOperationRequest { get; set; }
    }
}
