//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.Poco
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTag
    {
        public int IdCustomerTags { get; set; }
        public Nullable<int> IdCustomerAccount { get; set; }
        public Nullable<int> IdTag { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
