//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.Poco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int IdPartner { get; set; }
        public string PartnerTypeCode { get; set; }
        public string CurrencyCode { get; set; }
        public int Balance { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual RefPartnerType RefPartnerType { get; set; }
        public virtual Reseller Reseller { get; set; }
        public virtual Wholesaler Wholesaler { get; set; }
    }
}
