//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.Poco
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerBalanceHistory
    {
        public int IdPatnerHistory { get; set; }
        public int IdPartnerAccount { get; set; }
        public System.DateTime HistoryDate { get; set; }
        public int OldBalance { get; set; }
        public int NewBalance { get; set; }
        public int Amount { get; set; }
    }
}
