//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.Poco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfert2Cash
    {
        public int IdTransfert2Cash { get; set; }
        public int IdPartnerAccount { get; set; }
        public int IdSendingTransfert2CashDetails { get; set; }
        public int IdReceiverTransfert2CashDetails { get; set; }
        public string CodeTransfertStatus { get; set; }
        public int Amount { get; set; }
    
        public virtual Partner Partner { get; set; }
    }
}
