//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService.ExShinobiSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShinobiWebResponse", Namespace="http://exshinobi.expressexchange.fr/")]
    [System.SerializableAttribute()]
    public partial class ShinobiWebResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KoloWin.CustomerService.ExShinobiSvc.TransferPartnerResponse PartnerResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Succes {
            get {
                return this.SuccesField;
            }
            set {
                if ((this.SuccesField.Equals(value) != true)) {
                    this.SuccesField = value;
                    this.RaisePropertyChanged("Succes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public KoloWin.CustomerService.ExShinobiSvc.TransferPartnerResponse PartnerResponse {
            get {
                return this.PartnerResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerResponseField, value) != true)) {
                    this.PartnerResponseField = value;
                    this.RaisePropertyChanged("PartnerResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferPartnerResponse", Namespace="http://exshinobi.expressexchange.fr/")]
    [System.SerializableAttribute()]
    public partial class TransferPartnerResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool OperationSuccesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescriptionField;
        
        private KoloWin.CustomerService.ExShinobiSvc.Partner SelectedPartnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string wr_transaction_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string wr_transaction_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        private System.DateTime transaction_dateField;
        
        private System.DateTime transaction_pay_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string originating_countryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string destination_countryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sending_amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string originating_currencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string destination_currencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customer_feeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string payout_amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string exchange_rateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sender_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sender_first_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sender_middle_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sender_last_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sender_countryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sender_cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sender_dobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sender_id_issuanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_first_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_middle_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_last_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_address_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_address_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_postcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_countryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_mobile_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_landline_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_email_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_momo_accountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_accounttype_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_accounttype_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_idtype_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_id_noField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string settlement_currencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string settlement_amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correspondent_commissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string settlement_exchange_rateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transaction_referenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string send_reason_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string send_reason_descField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_country_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bank_accountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bank_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bank_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string local_bank_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string swift_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bank_branch_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bank_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bank_cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bank_countryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IbanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool OperationSucces {
            get {
                return this.OperationSuccesField;
            }
            set {
                if ((this.OperationSuccesField.Equals(value) != true)) {
                    this.OperationSuccesField = value;
                    this.RaisePropertyChanged("OperationSucces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorDescription {
            get {
                return this.ErrorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionField, value) != true)) {
                    this.ErrorDescriptionField = value;
                    this.RaisePropertyChanged("ErrorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public KoloWin.CustomerService.ExShinobiSvc.Partner SelectedPartner {
            get {
                return this.SelectedPartnerField;
            }
            set {
                if ((this.SelectedPartnerField.Equals(value) != true)) {
                    this.SelectedPartnerField = value;
                    this.RaisePropertyChanged("SelectedPartner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string wr_transaction_id {
            get {
                return this.wr_transaction_idField;
            }
            set {
                if ((object.ReferenceEquals(this.wr_transaction_idField, value) != true)) {
                    this.wr_transaction_idField = value;
                    this.RaisePropertyChanged("wr_transaction_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string wr_transaction_number {
            get {
                return this.wr_transaction_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.wr_transaction_numberField, value) != true)) {
                    this.wr_transaction_numberField = value;
                    this.RaisePropertyChanged("wr_transaction_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime transaction_date {
            get {
                return this.transaction_dateField;
            }
            set {
                if ((this.transaction_dateField.Equals(value) != true)) {
                    this.transaction_dateField = value;
                    this.RaisePropertyChanged("transaction_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime transaction_pay_date {
            get {
                return this.transaction_pay_dateField;
            }
            set {
                if ((this.transaction_pay_dateField.Equals(value) != true)) {
                    this.transaction_pay_dateField = value;
                    this.RaisePropertyChanged("transaction_pay_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string originating_country {
            get {
                return this.originating_countryField;
            }
            set {
                if ((object.ReferenceEquals(this.originating_countryField, value) != true)) {
                    this.originating_countryField = value;
                    this.RaisePropertyChanged("originating_country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string destination_country {
            get {
                return this.destination_countryField;
            }
            set {
                if ((object.ReferenceEquals(this.destination_countryField, value) != true)) {
                    this.destination_countryField = value;
                    this.RaisePropertyChanged("destination_country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string sending_amount {
            get {
                return this.sending_amountField;
            }
            set {
                if ((object.ReferenceEquals(this.sending_amountField, value) != true)) {
                    this.sending_amountField = value;
                    this.RaisePropertyChanged("sending_amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string originating_currency {
            get {
                return this.originating_currencyField;
            }
            set {
                if ((object.ReferenceEquals(this.originating_currencyField, value) != true)) {
                    this.originating_currencyField = value;
                    this.RaisePropertyChanged("originating_currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string destination_currency {
            get {
                return this.destination_currencyField;
            }
            set {
                if ((object.ReferenceEquals(this.destination_currencyField, value) != true)) {
                    this.destination_currencyField = value;
                    this.RaisePropertyChanged("destination_currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string customer_fee {
            get {
                return this.customer_feeField;
            }
            set {
                if ((object.ReferenceEquals(this.customer_feeField, value) != true)) {
                    this.customer_feeField = value;
                    this.RaisePropertyChanged("customer_fee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string payout_amount {
            get {
                return this.payout_amountField;
            }
            set {
                if ((object.ReferenceEquals(this.payout_amountField, value) != true)) {
                    this.payout_amountField = value;
                    this.RaisePropertyChanged("payout_amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string exchange_rate {
            get {
                return this.exchange_rateField;
            }
            set {
                if ((object.ReferenceEquals(this.exchange_rateField, value) != true)) {
                    this.exchange_rateField = value;
                    this.RaisePropertyChanged("exchange_rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string sender_id {
            get {
                return this.sender_idField;
            }
            set {
                if ((object.ReferenceEquals(this.sender_idField, value) != true)) {
                    this.sender_idField = value;
                    this.RaisePropertyChanged("sender_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string sender_first_name {
            get {
                return this.sender_first_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.sender_first_nameField, value) != true)) {
                    this.sender_first_nameField = value;
                    this.RaisePropertyChanged("sender_first_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string sender_middle_name {
            get {
                return this.sender_middle_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.sender_middle_nameField, value) != true)) {
                    this.sender_middle_nameField = value;
                    this.RaisePropertyChanged("sender_middle_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string sender_last_name {
            get {
                return this.sender_last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.sender_last_nameField, value) != true)) {
                    this.sender_last_nameField = value;
                    this.RaisePropertyChanged("sender_last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string sender_country {
            get {
                return this.sender_countryField;
            }
            set {
                if ((object.ReferenceEquals(this.sender_countryField, value) != true)) {
                    this.sender_countryField = value;
                    this.RaisePropertyChanged("sender_country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string sender_city {
            get {
                return this.sender_cityField;
            }
            set {
                if ((object.ReferenceEquals(this.sender_cityField, value) != true)) {
                    this.sender_cityField = value;
                    this.RaisePropertyChanged("sender_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string sender_dob {
            get {
                return this.sender_dobField;
            }
            set {
                if ((object.ReferenceEquals(this.sender_dobField, value) != true)) {
                    this.sender_dobField = value;
                    this.RaisePropertyChanged("sender_dob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string sender_id_issuance {
            get {
                return this.sender_id_issuanceField;
            }
            set {
                if ((object.ReferenceEquals(this.sender_id_issuanceField, value) != true)) {
                    this.sender_id_issuanceField = value;
                    this.RaisePropertyChanged("sender_id_issuance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string receiver_first_name {
            get {
                return this.receiver_first_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_first_nameField, value) != true)) {
                    this.receiver_first_nameField = value;
                    this.RaisePropertyChanged("receiver_first_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string receiver_middle_name {
            get {
                return this.receiver_middle_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_middle_nameField, value) != true)) {
                    this.receiver_middle_nameField = value;
                    this.RaisePropertyChanged("receiver_middle_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string receiver_last_name {
            get {
                return this.receiver_last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_last_nameField, value) != true)) {
                    this.receiver_last_nameField = value;
                    this.RaisePropertyChanged("receiver_last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string receiver_address_1 {
            get {
                return this.receiver_address_1Field;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_address_1Field, value) != true)) {
                    this.receiver_address_1Field = value;
                    this.RaisePropertyChanged("receiver_address_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string receiver_address_2 {
            get {
                return this.receiver_address_2Field;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_address_2Field, value) != true)) {
                    this.receiver_address_2Field = value;
                    this.RaisePropertyChanged("receiver_address_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string receiver_city {
            get {
                return this.receiver_cityField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_cityField, value) != true)) {
                    this.receiver_cityField = value;
                    this.RaisePropertyChanged("receiver_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string receiver_state {
            get {
                return this.receiver_stateField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_stateField, value) != true)) {
                    this.receiver_stateField = value;
                    this.RaisePropertyChanged("receiver_state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string receiver_postcode {
            get {
                return this.receiver_postcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_postcodeField, value) != true)) {
                    this.receiver_postcodeField = value;
                    this.RaisePropertyChanged("receiver_postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string receiver_country {
            get {
                return this.receiver_countryField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_countryField, value) != true)) {
                    this.receiver_countryField = value;
                    this.RaisePropertyChanged("receiver_country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string receiver_mobile_number {
            get {
                return this.receiver_mobile_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_mobile_numberField, value) != true)) {
                    this.receiver_mobile_numberField = value;
                    this.RaisePropertyChanged("receiver_mobile_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string receiver_landline_number {
            get {
                return this.receiver_landline_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_landline_numberField, value) != true)) {
                    this.receiver_landline_numberField = value;
                    this.RaisePropertyChanged("receiver_landline_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string receiver_email_id {
            get {
                return this.receiver_email_idField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_email_idField, value) != true)) {
                    this.receiver_email_idField = value;
                    this.RaisePropertyChanged("receiver_email_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string receiver_momo_account {
            get {
                return this.receiver_momo_accountField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_momo_accountField, value) != true)) {
                    this.receiver_momo_accountField = value;
                    this.RaisePropertyChanged("receiver_momo_account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string receiver_accounttype_name {
            get {
                return this.receiver_accounttype_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_accounttype_nameField, value) != true)) {
                    this.receiver_accounttype_nameField = value;
                    this.RaisePropertyChanged("receiver_accounttype_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string receiver_accounttype_code {
            get {
                return this.receiver_accounttype_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_accounttype_codeField, value) != true)) {
                    this.receiver_accounttype_codeField = value;
                    this.RaisePropertyChanged("receiver_accounttype_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string receiver_idtype_name {
            get {
                return this.receiver_idtype_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_idtype_nameField, value) != true)) {
                    this.receiver_idtype_nameField = value;
                    this.RaisePropertyChanged("receiver_idtype_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string receiver_id_no {
            get {
                return this.receiver_id_noField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_id_noField, value) != true)) {
                    this.receiver_id_noField = value;
                    this.RaisePropertyChanged("receiver_id_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string settlement_currency {
            get {
                return this.settlement_currencyField;
            }
            set {
                if ((object.ReferenceEquals(this.settlement_currencyField, value) != true)) {
                    this.settlement_currencyField = value;
                    this.RaisePropertyChanged("settlement_currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string settlement_amount {
            get {
                return this.settlement_amountField;
            }
            set {
                if ((object.ReferenceEquals(this.settlement_amountField, value) != true)) {
                    this.settlement_amountField = value;
                    this.RaisePropertyChanged("settlement_amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string correspondent_commission {
            get {
                return this.correspondent_commissionField;
            }
            set {
                if ((object.ReferenceEquals(this.correspondent_commissionField, value) != true)) {
                    this.correspondent_commissionField = value;
                    this.RaisePropertyChanged("correspondent_commission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string settlement_exchange_rate {
            get {
                return this.settlement_exchange_rateField;
            }
            set {
                if ((object.ReferenceEquals(this.settlement_exchange_rateField, value) != true)) {
                    this.settlement_exchange_rateField = value;
                    this.RaisePropertyChanged("settlement_exchange_rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=46)]
        public string transaction_reference {
            get {
                return this.transaction_referenceField;
            }
            set {
                if ((object.ReferenceEquals(this.transaction_referenceField, value) != true)) {
                    this.transaction_referenceField = value;
                    this.RaisePropertyChanged("transaction_reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=47)]
        public string send_reason_code {
            get {
                return this.send_reason_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.send_reason_codeField, value) != true)) {
                    this.send_reason_codeField = value;
                    this.RaisePropertyChanged("send_reason_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=48)]
        public string send_reason_desc {
            get {
                return this.send_reason_descField;
            }
            set {
                if ((object.ReferenceEquals(this.send_reason_descField, value) != true)) {
                    this.send_reason_descField = value;
                    this.RaisePropertyChanged("send_reason_desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=49)]
        public string receiver_country_code {
            get {
                return this.receiver_country_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_country_codeField, value) != true)) {
                    this.receiver_country_codeField = value;
                    this.RaisePropertyChanged("receiver_country_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=50)]
        public string bank_account {
            get {
                return this.bank_accountField;
            }
            set {
                if ((object.ReferenceEquals(this.bank_accountField, value) != true)) {
                    this.bank_accountField = value;
                    this.RaisePropertyChanged("bank_account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=51)]
        public string bank_name {
            get {
                return this.bank_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.bank_nameField, value) != true)) {
                    this.bank_nameField = value;
                    this.RaisePropertyChanged("bank_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=52)]
        public string bank_code {
            get {
                return this.bank_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.bank_codeField, value) != true)) {
                    this.bank_codeField = value;
                    this.RaisePropertyChanged("bank_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=53)]
        public string local_bank_code {
            get {
                return this.local_bank_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.local_bank_codeField, value) != true)) {
                    this.local_bank_codeField = value;
                    this.RaisePropertyChanged("local_bank_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=54)]
        public string swift_code {
            get {
                return this.swift_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.swift_codeField, value) != true)) {
                    this.swift_codeField = value;
                    this.RaisePropertyChanged("swift_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=55)]
        public string bank_branch_name {
            get {
                return this.bank_branch_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.bank_branch_nameField, value) != true)) {
                    this.bank_branch_nameField = value;
                    this.RaisePropertyChanged("bank_branch_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=56)]
        public string bank_address {
            get {
                return this.bank_addressField;
            }
            set {
                if ((object.ReferenceEquals(this.bank_addressField, value) != true)) {
                    this.bank_addressField = value;
                    this.RaisePropertyChanged("bank_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=57)]
        public string bank_city {
            get {
                return this.bank_cityField;
            }
            set {
                if ((object.ReferenceEquals(this.bank_cityField, value) != true)) {
                    this.bank_cityField = value;
                    this.RaisePropertyChanged("bank_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=58)]
        public string bank_country {
            get {
                return this.bank_countryField;
            }
            set {
                if ((object.ReferenceEquals(this.bank_countryField, value) != true)) {
                    this.bank_countryField = value;
                    this.RaisePropertyChanged("bank_country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=59)]
        public string Iban {
            get {
                return this.IbanField;
            }
            set {
                if ((object.ReferenceEquals(this.IbanField, value) != true)) {
                    this.IbanField = value;
                    this.RaisePropertyChanged("Iban");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Partner", Namespace="http://exshinobi.expressexchange.fr/")]
    public enum Partner : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WORLDREMIT = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ECOBANK = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://exshinobi.expressexchange.fr/", ConfigurationName="ExShinobiSvc.ExShinobiSoap")]
    public interface ExShinobiSoap {
        
        // CODEGEN: Generating message contract since element name selectedPartner from namespace http://exshinobi.expressexchange.fr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://exshinobi.expressexchange.fr/FindTransaction", ReplyAction="*")]
        KoloWin.CustomerService.ExShinobiSvc.FindTransactionResponse FindTransaction(KoloWin.CustomerService.ExShinobiSvc.FindTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exshinobi.expressexchange.fr/FindTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExShinobiSvc.FindTransactionResponse> FindTransactionAsync(KoloWin.CustomerService.ExShinobiSvc.FindTransactionRequest request);
        
        // CODEGEN: Generating message contract since element name selectedPartner from namespace http://exshinobi.expressexchange.fr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://exshinobi.expressexchange.fr/PayTransaction", ReplyAction="*")]
        KoloWin.CustomerService.ExShinobiSvc.PayTransactionResponse PayTransaction(KoloWin.CustomerService.ExShinobiSvc.PayTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exshinobi.expressexchange.fr/PayTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExShinobiSvc.PayTransactionResponse> PayTransactionAsync(KoloWin.CustomerService.ExShinobiSvc.PayTransactionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindTransaction", Namespace="http://exshinobi.expressexchange.fr/", Order=0)]
        public KoloWin.CustomerService.ExShinobiSvc.FindTransactionRequestBody Body;
        
        public FindTransactionRequest() {
        }
        
        public FindTransactionRequest(KoloWin.CustomerService.ExShinobiSvc.FindTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exshinobi.expressexchange.fr/")]
    public partial class FindTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectedPartner;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string code;
        
        public FindTransactionRequestBody() {
        }
        
        public FindTransactionRequestBody(string selectedPartner, string code) {
            this.selectedPartner = selectedPartner;
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindTransactionResponse", Namespace="http://exshinobi.expressexchange.fr/", Order=0)]
        public KoloWin.CustomerService.ExShinobiSvc.FindTransactionResponseBody Body;
        
        public FindTransactionResponse() {
        }
        
        public FindTransactionResponse(KoloWin.CustomerService.ExShinobiSvc.FindTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exshinobi.expressexchange.fr/")]
    public partial class FindTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KoloWin.CustomerService.ExShinobiSvc.ShinobiWebResponse FindTransactionResult;
        
        public FindTransactionResponseBody() {
        }
        
        public FindTransactionResponseBody(KoloWin.CustomerService.ExShinobiSvc.ShinobiWebResponse FindTransactionResult) {
            this.FindTransactionResult = FindTransactionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayTransaction", Namespace="http://exshinobi.expressexchange.fr/", Order=0)]
        public KoloWin.CustomerService.ExShinobiSvc.PayTransactionRequestBody Body;
        
        public PayTransactionRequest() {
        }
        
        public PayTransactionRequest(KoloWin.CustomerService.ExShinobiSvc.PayTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exshinobi.expressexchange.fr/")]
    public partial class PayTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectedPartner;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string noPieceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int managerIdType;
        
        public PayTransactionRequestBody() {
        }
        
        public PayTransactionRequestBody(string selectedPartner, string code, string noPieceId, int managerIdType) {
            this.selectedPartner = selectedPartner;
            this.code = code;
            this.noPieceId = noPieceId;
            this.managerIdType = managerIdType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayTransactionResponse", Namespace="http://exshinobi.expressexchange.fr/", Order=0)]
        public KoloWin.CustomerService.ExShinobiSvc.PayTransactionResponseBody Body;
        
        public PayTransactionResponse() {
        }
        
        public PayTransactionResponse(KoloWin.CustomerService.ExShinobiSvc.PayTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exshinobi.expressexchange.fr/")]
    public partial class PayTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KoloWin.CustomerService.ExShinobiSvc.ShinobiWebResponse PayTransactionResult;
        
        public PayTransactionResponseBody() {
        }
        
        public PayTransactionResponseBody(KoloWin.CustomerService.ExShinobiSvc.ShinobiWebResponse PayTransactionResult) {
            this.PayTransactionResult = PayTransactionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExShinobiSoapChannel : KoloWin.CustomerService.ExShinobiSvc.ExShinobiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExShinobiSoapClient : System.ServiceModel.ClientBase<KoloWin.CustomerService.ExShinobiSvc.ExShinobiSoap>, KoloWin.CustomerService.ExShinobiSvc.ExShinobiSoap {
        
        public ExShinobiSoapClient() {
        }
        
        public ExShinobiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExShinobiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExShinobiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExShinobiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KoloWin.CustomerService.ExShinobiSvc.FindTransactionResponse KoloWin.CustomerService.ExShinobiSvc.ExShinobiSoap.FindTransaction(KoloWin.CustomerService.ExShinobiSvc.FindTransactionRequest request) {
            return base.Channel.FindTransaction(request);
        }
        
        public KoloWin.CustomerService.ExShinobiSvc.ShinobiWebResponse FindTransaction(string selectedPartner, string code) {
            KoloWin.CustomerService.ExShinobiSvc.FindTransactionRequest inValue = new KoloWin.CustomerService.ExShinobiSvc.FindTransactionRequest();
            inValue.Body = new KoloWin.CustomerService.ExShinobiSvc.FindTransactionRequestBody();
            inValue.Body.selectedPartner = selectedPartner;
            inValue.Body.code = code;
            KoloWin.CustomerService.ExShinobiSvc.FindTransactionResponse retVal = ((KoloWin.CustomerService.ExShinobiSvc.ExShinobiSoap)(this)).FindTransaction(inValue);
            return retVal.Body.FindTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExShinobiSvc.FindTransactionResponse> KoloWin.CustomerService.ExShinobiSvc.ExShinobiSoap.FindTransactionAsync(KoloWin.CustomerService.ExShinobiSvc.FindTransactionRequest request) {
            return base.Channel.FindTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<KoloWin.CustomerService.ExShinobiSvc.FindTransactionResponse> FindTransactionAsync(string selectedPartner, string code) {
            KoloWin.CustomerService.ExShinobiSvc.FindTransactionRequest inValue = new KoloWin.CustomerService.ExShinobiSvc.FindTransactionRequest();
            inValue.Body = new KoloWin.CustomerService.ExShinobiSvc.FindTransactionRequestBody();
            inValue.Body.selectedPartner = selectedPartner;
            inValue.Body.code = code;
            return ((KoloWin.CustomerService.ExShinobiSvc.ExShinobiSoap)(this)).FindTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KoloWin.CustomerService.ExShinobiSvc.PayTransactionResponse KoloWin.CustomerService.ExShinobiSvc.ExShinobiSoap.PayTransaction(KoloWin.CustomerService.ExShinobiSvc.PayTransactionRequest request) {
            return base.Channel.PayTransaction(request);
        }
        
        public KoloWin.CustomerService.ExShinobiSvc.ShinobiWebResponse PayTransaction(string selectedPartner, string code, string noPieceId, int managerIdType) {
            KoloWin.CustomerService.ExShinobiSvc.PayTransactionRequest inValue = new KoloWin.CustomerService.ExShinobiSvc.PayTransactionRequest();
            inValue.Body = new KoloWin.CustomerService.ExShinobiSvc.PayTransactionRequestBody();
            inValue.Body.selectedPartner = selectedPartner;
            inValue.Body.code = code;
            inValue.Body.noPieceId = noPieceId;
            inValue.Body.managerIdType = managerIdType;
            KoloWin.CustomerService.ExShinobiSvc.PayTransactionResponse retVal = ((KoloWin.CustomerService.ExShinobiSvc.ExShinobiSoap)(this)).PayTransaction(inValue);
            return retVal.Body.PayTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExShinobiSvc.PayTransactionResponse> KoloWin.CustomerService.ExShinobiSvc.ExShinobiSoap.PayTransactionAsync(KoloWin.CustomerService.ExShinobiSvc.PayTransactionRequest request) {
            return base.Channel.PayTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<KoloWin.CustomerService.ExShinobiSvc.PayTransactionResponse> PayTransactionAsync(string selectedPartner, string code, string noPieceId, int managerIdType) {
            KoloWin.CustomerService.ExShinobiSvc.PayTransactionRequest inValue = new KoloWin.CustomerService.ExShinobiSvc.PayTransactionRequest();
            inValue.Body = new KoloWin.CustomerService.ExShinobiSvc.PayTransactionRequestBody();
            inValue.Body.selectedPartner = selectedPartner;
            inValue.Body.code = code;
            inValue.Body.noPieceId = noPieceId;
            inValue.Body.managerIdType = managerIdType;
            return ((KoloWin.CustomerService.ExShinobiSvc.ExShinobiSoap)(this)).PayTransactionAsync(inValue);
        }
    }
}
