//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.PocoAndroid
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessContact
    {
        public int IdBusiness { get; set; }
        public int IdContact { get; set; }
        public string JobTitle { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Person Person { get; set; }
    }
}
