//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.PocoAndroid
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerGroup
    {
        public int IdCustomerGroup { get; set; }
        public int IdMemberCustomer { get; set; }
        public string GroupTypeCode { get; set; }
        public string GroupName { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual RefGroupType RefGroupType { get; set; }
        public virtual GroupImage GroupImage { get; set; }
    }
}
