//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloWin.CustomerService.ExWebSvc4ExTools {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnpaidBill", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UnpaidBill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BilledCustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillAccountIdField;
        
        private System.DateTime BillGenerationDateField;
        
        private System.DateTime BillDueDateField;
        
        private decimal BillAmountField;
        
        private System.Nullable<System.DateTime> ImportationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestedOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumCompteurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ref4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ref5Field;
        
        private System.Nullable<int> StatutField;
        
        private System.Nullable<decimal> FraisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BillNumber {
            get {
                return this.BillNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BillNumberField, value) != true)) {
                    this.BillNumberField = value;
                    this.RaisePropertyChanged("BillNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BillerId {
            get {
                return this.BillerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BillerIdField, value) != true)) {
                    this.BillerIdField = value;
                    this.RaisePropertyChanged("BillerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BilledCustomerId {
            get {
                return this.BilledCustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BilledCustomerIdField, value) != true)) {
                    this.BilledCustomerIdField = value;
                    this.RaisePropertyChanged("BilledCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BillAccountId {
            get {
                return this.BillAccountIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BillAccountIdField, value) != true)) {
                    this.BillAccountIdField = value;
                    this.RaisePropertyChanged("BillAccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime BillGenerationDate {
            get {
                return this.BillGenerationDateField;
            }
            set {
                if ((this.BillGenerationDateField.Equals(value) != true)) {
                    this.BillGenerationDateField = value;
                    this.RaisePropertyChanged("BillGenerationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime BillDueDate {
            get {
                return this.BillDueDateField;
            }
            set {
                if ((this.BillDueDateField.Equals(value) != true)) {
                    this.BillDueDateField = value;
                    this.RaisePropertyChanged("BillDueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal BillAmount {
            get {
                return this.BillAmountField;
            }
            set {
                if ((this.BillAmountField.Equals(value) != true)) {
                    this.BillAmountField = value;
                    this.RaisePropertyChanged("BillAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> ImportationDate {
            get {
                return this.ImportationDateField;
            }
            set {
                if ((this.ImportationDateField.Equals(value) != true)) {
                    this.ImportationDateField = value;
                    this.RaisePropertyChanged("ImportationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string RequestedOperation {
            get {
                return this.RequestedOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedOperationField, value) != true)) {
                    this.RequestedOperationField = value;
                    this.RaisePropertyChanged("RequestedOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string NumCompteur {
            get {
                return this.NumCompteurField;
            }
            set {
                if ((object.ReferenceEquals(this.NumCompteurField, value) != true)) {
                    this.NumCompteurField = value;
                    this.RaisePropertyChanged("NumCompteur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Ref4 {
            get {
                return this.Ref4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Ref4Field, value) != true)) {
                    this.Ref4Field = value;
                    this.RaisePropertyChanged("Ref4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Ref5 {
            get {
                return this.Ref5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Ref5Field, value) != true)) {
                    this.Ref5Field = value;
                    this.RaisePropertyChanged("Ref5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<int> Statut {
            get {
                return this.StatutField;
            }
            set {
                if ((this.StatutField.Equals(value) != true)) {
                    this.StatutField = value;
                    this.RaisePropertyChanged("Statut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<decimal> Frais {
            get {
                return this.FraisField;
            }
            set {
                if ((this.FraisField.Equals(value) != true)) {
                    this.FraisField = value;
                    this.RaisePropertyChanged("Frais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExWebSvc4ExTools.WebService4KoloSoap")]
    public interface WebService4KoloSoap {
        
        // CODEGEN: Generating message contract since element name codeTerm from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEneoByBillNumber", ReplyAction="*")]
        KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberResponse FindEneoByBillNumber(KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEneoByBillNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberResponse> FindEneoByBillNumberAsync(KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberRequest request);
        
        // CODEGEN: Generating message contract since element name codeTerm from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PayENEO", ReplyAction="*")]
        KoloWin.CustomerService.ExWebSvc4ExTools.PayENEOResponse PayENEO(KoloWin.CustomerService.ExWebSvc4ExTools.PayENEORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PayENEO", ReplyAction="*")]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4ExTools.PayENEOResponse> PayENEOAsync(KoloWin.CustomerService.ExWebSvc4ExTools.PayENEORequest request);
        
        // CODEGEN: Generating message contract since element name codeTerm from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEneoByBillAccount", ReplyAction="*")]
        KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountResponse FindEneoByBillAccount(KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEneoByBillAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountResponse> FindEneoByBillAccountAsync(KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindEneoByBillNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindEneoByBillNumber", Namespace="http://tempuri.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberRequestBody Body;
        
        public FindEneoByBillNumberRequest() {
        }
        
        public FindEneoByBillNumberRequest(KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindEneoByBillNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codeTerm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passTerm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string codeUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string passUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string numeroFacture;
        
        public FindEneoByBillNumberRequestBody() {
        }
        
        public FindEneoByBillNumberRequestBody(string codeTerm, string passTerm, string codeUser, string passUser, string numeroFacture) {
            this.codeTerm = codeTerm;
            this.passTerm = passTerm;
            this.codeUser = codeUser;
            this.passUser = passUser;
            this.numeroFacture = numeroFacture;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindEneoByBillNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindEneoByBillNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberResponseBody Body;
        
        public FindEneoByBillNumberResponse() {
        }
        
        public FindEneoByBillNumberResponse(KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindEneoByBillNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KoloWin.CustomerService.ExWebSvc4ExTools.UnpaidBill FindEneoByBillNumberResult;
        
        public FindEneoByBillNumberResponseBody() {
        }
        
        public FindEneoByBillNumberResponseBody(KoloWin.CustomerService.ExWebSvc4ExTools.UnpaidBill FindEneoByBillNumberResult) {
            this.FindEneoByBillNumberResult = FindEneoByBillNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayENEORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayENEO", Namespace="http://tempuri.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4ExTools.PayENEORequestBody Body;
        
        public PayENEORequest() {
        }
        
        public PayENEORequest(KoloWin.CustomerService.ExWebSvc4ExTools.PayENEORequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PayENEORequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codeTerm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passTerm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string codeUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string passUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string numeroFacture;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string nomDuRemettant;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string telephone;
        
        public PayENEORequestBody() {
        }
        
        public PayENEORequestBody(string codeTerm, string passTerm, string codeUser, string passUser, string numeroFacture, string nomDuRemettant, string telephone) {
            this.codeTerm = codeTerm;
            this.passTerm = passTerm;
            this.codeUser = codeUser;
            this.passUser = passUser;
            this.numeroFacture = numeroFacture;
            this.nomDuRemettant = nomDuRemettant;
            this.telephone = telephone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayENEOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayENEOResponse", Namespace="http://tempuri.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4ExTools.PayENEOResponseBody Body;
        
        public PayENEOResponse() {
        }
        
        public PayENEOResponse(KoloWin.CustomerService.ExWebSvc4ExTools.PayENEOResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PayENEOResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PayENEOResult;
        
        public PayENEOResponseBody() {
        }
        
        public PayENEOResponseBody(string PayENEOResult) {
            this.PayENEOResult = PayENEOResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindEneoByBillAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindEneoByBillAccount", Namespace="http://tempuri.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountRequestBody Body;
        
        public FindEneoByBillAccountRequest() {
        }
        
        public FindEneoByBillAccountRequest(KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindEneoByBillAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codeTerm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passTerm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string codeUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string passUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string numeroContrat;
        
        public FindEneoByBillAccountRequestBody() {
        }
        
        public FindEneoByBillAccountRequestBody(string codeTerm, string passTerm, string codeUser, string passUser, string numeroContrat) {
            this.codeTerm = codeTerm;
            this.passTerm = passTerm;
            this.codeUser = codeUser;
            this.passUser = passUser;
            this.numeroContrat = numeroContrat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindEneoByBillAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindEneoByBillAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountResponseBody Body;
        
        public FindEneoByBillAccountResponse() {
        }
        
        public FindEneoByBillAccountResponse(KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindEneoByBillAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KoloWin.CustomerService.ExWebSvc4ExTools.UnpaidBill[] FindEneoByBillAccountResult;
        
        public FindEneoByBillAccountResponseBody() {
        }
        
        public FindEneoByBillAccountResponseBody(KoloWin.CustomerService.ExWebSvc4ExTools.UnpaidBill[] FindEneoByBillAccountResult) {
            this.FindEneoByBillAccountResult = FindEneoByBillAccountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService4KoloSoapChannel : KoloWin.CustomerService.ExWebSvc4ExTools.WebService4KoloSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService4KoloSoapClient : System.ServiceModel.ClientBase<KoloWin.CustomerService.ExWebSvc4ExTools.WebService4KoloSoap>, KoloWin.CustomerService.ExWebSvc4ExTools.WebService4KoloSoap {
        
        public WebService4KoloSoapClient() {
        }
        
        public WebService4KoloSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService4KoloSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService4KoloSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService4KoloSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberResponse KoloWin.CustomerService.ExWebSvc4ExTools.WebService4KoloSoap.FindEneoByBillNumber(KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberRequest request) {
            return base.Channel.FindEneoByBillNumber(request);
        }
        
        public KoloWin.CustomerService.ExWebSvc4ExTools.UnpaidBill FindEneoByBillNumber(string codeTerm, string passTerm, string codeUser, string passUser, string numeroFacture) {
            KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberRequest inValue = new KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberRequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberRequestBody();
            inValue.Body.codeTerm = codeTerm;
            inValue.Body.passTerm = passTerm;
            inValue.Body.codeUser = codeUser;
            inValue.Body.passUser = passUser;
            inValue.Body.numeroFacture = numeroFacture;
            KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberResponse retVal = ((KoloWin.CustomerService.ExWebSvc4ExTools.WebService4KoloSoap)(this)).FindEneoByBillNumber(inValue);
            return retVal.Body.FindEneoByBillNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberResponse> KoloWin.CustomerService.ExWebSvc4ExTools.WebService4KoloSoap.FindEneoByBillNumberAsync(KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberRequest request) {
            return base.Channel.FindEneoByBillNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberResponse> FindEneoByBillNumberAsync(string codeTerm, string passTerm, string codeUser, string passUser, string numeroFacture) {
            KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberRequest inValue = new KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberRequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillNumberRequestBody();
            inValue.Body.codeTerm = codeTerm;
            inValue.Body.passTerm = passTerm;
            inValue.Body.codeUser = codeUser;
            inValue.Body.passUser = passUser;
            inValue.Body.numeroFacture = numeroFacture;
            return ((KoloWin.CustomerService.ExWebSvc4ExTools.WebService4KoloSoap)(this)).FindEneoByBillNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KoloWin.CustomerService.ExWebSvc4ExTools.PayENEOResponse KoloWin.CustomerService.ExWebSvc4ExTools.WebService4KoloSoap.PayENEO(KoloWin.CustomerService.ExWebSvc4ExTools.PayENEORequest request) {
            return base.Channel.PayENEO(request);
        }
        
        public string PayENEO(string codeTerm, string passTerm, string codeUser, string passUser, string numeroFacture, string nomDuRemettant, string telephone) {
            KoloWin.CustomerService.ExWebSvc4ExTools.PayENEORequest inValue = new KoloWin.CustomerService.ExWebSvc4ExTools.PayENEORequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4ExTools.PayENEORequestBody();
            inValue.Body.codeTerm = codeTerm;
            inValue.Body.passTerm = passTerm;
            inValue.Body.codeUser = codeUser;
            inValue.Body.passUser = passUser;
            inValue.Body.numeroFacture = numeroFacture;
            inValue.Body.nomDuRemettant = nomDuRemettant;
            inValue.Body.telephone = telephone;
            KoloWin.CustomerService.ExWebSvc4ExTools.PayENEOResponse retVal = ((KoloWin.CustomerService.ExWebSvc4ExTools.WebService4KoloSoap)(this)).PayENEO(inValue);
            return retVal.Body.PayENEOResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4ExTools.PayENEOResponse> KoloWin.CustomerService.ExWebSvc4ExTools.WebService4KoloSoap.PayENEOAsync(KoloWin.CustomerService.ExWebSvc4ExTools.PayENEORequest request) {
            return base.Channel.PayENEOAsync(request);
        }
        
        public System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4ExTools.PayENEOResponse> PayENEOAsync(string codeTerm, string passTerm, string codeUser, string passUser, string numeroFacture, string nomDuRemettant, string telephone) {
            KoloWin.CustomerService.ExWebSvc4ExTools.PayENEORequest inValue = new KoloWin.CustomerService.ExWebSvc4ExTools.PayENEORequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4ExTools.PayENEORequestBody();
            inValue.Body.codeTerm = codeTerm;
            inValue.Body.passTerm = passTerm;
            inValue.Body.codeUser = codeUser;
            inValue.Body.passUser = passUser;
            inValue.Body.numeroFacture = numeroFacture;
            inValue.Body.nomDuRemettant = nomDuRemettant;
            inValue.Body.telephone = telephone;
            return ((KoloWin.CustomerService.ExWebSvc4ExTools.WebService4KoloSoap)(this)).PayENEOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountResponse KoloWin.CustomerService.ExWebSvc4ExTools.WebService4KoloSoap.FindEneoByBillAccount(KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountRequest request) {
            return base.Channel.FindEneoByBillAccount(request);
        }
        
        public KoloWin.CustomerService.ExWebSvc4ExTools.UnpaidBill[] FindEneoByBillAccount(string codeTerm, string passTerm, string codeUser, string passUser, string numeroContrat) {
            KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountRequest inValue = new KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountRequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountRequestBody();
            inValue.Body.codeTerm = codeTerm;
            inValue.Body.passTerm = passTerm;
            inValue.Body.codeUser = codeUser;
            inValue.Body.passUser = passUser;
            inValue.Body.numeroContrat = numeroContrat;
            KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountResponse retVal = ((KoloWin.CustomerService.ExWebSvc4ExTools.WebService4KoloSoap)(this)).FindEneoByBillAccount(inValue);
            return retVal.Body.FindEneoByBillAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountResponse> KoloWin.CustomerService.ExWebSvc4ExTools.WebService4KoloSoap.FindEneoByBillAccountAsync(KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountRequest request) {
            return base.Channel.FindEneoByBillAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountResponse> FindEneoByBillAccountAsync(string codeTerm, string passTerm, string codeUser, string passUser, string numeroContrat) {
            KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountRequest inValue = new KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountRequest();
            inValue.Body = new KoloWin.CustomerService.ExWebSvc4ExTools.FindEneoByBillAccountRequestBody();
            inValue.Body.codeTerm = codeTerm;
            inValue.Body.passTerm = passTerm;
            inValue.Body.codeUser = codeUser;
            inValue.Body.passUser = passUser;
            inValue.Body.numeroContrat = numeroContrat;
            return ((KoloWin.CustomerService.ExWebSvc4ExTools.WebService4KoloSoap)(this)).FindEneoByBillAccountAsync(inValue);
        }
    }
}
